### ISSUE TITLE
Please upgrade to latest Zeebe version

### ISSUE THREAD

**Issue by sherry-ummen** [camunda-community-hub/spring-zeebe#127]
Hi,

Could we have the latest version of Zeebe as well :)

I am not very familier with pom files so not sure what changes are needed

**Comment by sherry-ummen** [comment]
looks like its again need new version to bump 1.2.4 ? Do you want me to make a new PR ? Btw its possible to have dependabpt enabled in this repo as well, will perhaps make easier to update the dependencies ? :)

**Comment by berndruecker** [comment]
A PR would be fantastic. Do you also want to add a dependabot config - otherwise I can take care of that - I like the idea!

**Comment by berndruecker** [comment]
And I just recognize I forgot to close this issue after releasing 1.2.1 successfully 🙈 Let's reuse it now :-)

**Comment by berndruecker** [comment]
Worked: https://github.com/camunda-community-hub/spring-zeebe/pull/139

**Comment by berndruecker** [comment]
Just also release 1.2.4
