### ISSUE TITLE
Make fetching of Job variables more convenient and DRY

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/spring-zeebe#132]
Instead of repeating variable names in the `fetchVariables` property of the `@ZeebeWorker` annotation and then later in the actual variable access, e.g.

```java
  @ZeebeWorker(type = "myType", fetchVariables = { "orderId" } )
  public void handleJob(final JobClient client, final ActivatedJob job) {
    String orderNumber = (String) job.getVariablesAsMap().get("orderId");
  }
```

we could keep it DRY (Don't Repeat Yourself) and convenient with an argument list, e.g.

```java
  @ZeebeWorker(type = "myType")
  public void handleJob(final JobClient client, final ActivatedJob job, String orderId) {
  }
```

Type casting would also be done implicitly here. Not sure if the additional parameter would have to be annotated to make this work.

**Comment by berndruecker** [comment]
Or probably?

`
@ZeebeWorker(type = "myType")
public void handleJob(final JobClient client, final ActivatedJob job, @ZeebeVariable String orderId) {
}
`

**Comment by falko** [comment]
Fine too. Either way, the signature of the method would have to change to allow an additional list of values.

Looking closer it doesn't seem to be a compiler-safe signature anyway.
Test case: https://github.com/camunda-community-hub/spring-zeebe/blob/master/client/spring-zeebe/src/test/java/io/camunda/zeebe/spring/client/bean/ClassInfoTest.java#L24
Invocation: https://github.com/camunda-community-hub/spring-zeebe/blob/master/client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/config/processor/ZeebeWorkerPostProcessor.java#L58

**Comment by Lzgabel** [comment]
Hi @falko @berndruecker , I've implemented the first version.  Can you review it and give me some suggestions?

**Comment by berndruecker** [comment]
Thanks @Lzgabel - see comments in PR. 
And marking for visibility that I am currently working on this issue now.

**Comment by berndruecker** [comment]
I added my stab in this branch, see readme: https://github.com/camunda-community-hub/spring-zeebe/tree/worker-convenience#fetch-variables

Quick poll: As soon as I use @ZeebeVariable I don't get all variables loaded into the map anymore, as this will be added to fetchVariables. If I want more variables I could add them to the "fetchVaariables". is that intuitive behavior? Or should that be independent of "fetchVariables" - and only if "fetchVariables" is set, also make sure these variables are added, but if it is empty, fetch all.

WDFYT @falko ?

**Comment by berndruecker** [comment]
And just FYI, I added https://github.com/camunda-community-hub/spring-zeebe/issues/143 to also look at auto-complete in probably the same PR

**Comment by Lzgabel** [comment]
> As soon as I use @ZeebeVariable I don't get all variables loaded into the map anymore, fetchVariables will be automatically applied. If I need more variables than annotated in the parameters, I could still use the "fetchVariables" to add them

Hey @berndruecker ,  I'll vote first one, because in most of our scenarios, each woker only needs to specify a few explicit variables.

**Comment by berndruecker** [comment]
OK - thanks, that is good input. I still try to figure out what is more intuitive and what can lead to more or less problems. I also thought about a config parameter in the annotation to be able to overwrite this default if required:

```
@ZeebeWorker(type = "myType")
public void handleJob(JobClient client, ActivatedJob job, @ZeebeVariable(limitVariableFetching=false) String orderId) {
```

**Comment by Lzgabel** [comment]
> @ZeebeWorker(type = "myType", fetchAllVariables=true)

@berndruecker I'll choose this option, WDYT?

**Comment by berndruecker** [comment]
I generally like that direction, but I am worried that this allows configuring wired things:
```
@ZeebeWorker(type = "myType", fetchVariables={"a", "b"}, fetchAllVariables=true)
```

But maybe I am too worried ;-) The above situation could raise an exception during startup as being invalid - or we simply say that "fetchAllVariables=true" always wins - which still make sense I guess
