### ISSUE TITLE
Getting processinstancekey as 'XXXXXXXXXXXXXXXX'

### ISSUE THREAD

**Issue by umesh-kushwaha** [camunda-community-hub/spring-zeebe#147]
I am trying to perform load test on workflow. I am using this client library to start the instance. I have a target of 100K rpm. Intermittently I am getting processInstanceKey='XXXXXXXXXXXXXXXX' in response. What does it mean ? Request was failed to start instance or something else.

**Comment by berndruecker** [comment]
Could you please ask questions in our forum at https://forum.camunda.io/? That would help streamline answering a lot. Thx!

**Comment by berndruecker** [comment]
And as a quick hint: It would be great to provide a little bit more detail: What environment (cloud or self-managed Zeebe)? How do you generate load? probably some code...

**Comment by falko** [comment]
For the record here is the forum post: https://forum.camunda.io/t/getting-processinstancekey-like-xxxxxxxxxxxxxxxx/2620 and sounds to be unrelated to spring-zeebe itself
