### ISSUE TITLE
some ideas about exception handling

### ISSUE THREAD

**Issue by lzgabel** [camunda-community-hub/spring-zeebe#153]
Hi @berndruecker, I have an idea about the exception handling strategy - `DefaultCommandExceptionHandlingStrategy `. We provide a default exception handling policy. If the user provides a custom exception handling policy, the custom policy will be activated.

* interface
```
public interface CommandExceptionHandlingStrategy {
  void handleCommandError(JobClient jobClient, ActivatedJob job, Throwable throwable);
}
```

* default handling strategy
```
public class DefaultCommandExceptionHandlingStrategy implements CommandExceptionHandlingStrategy {

  @Override
  public void handleCommandError(JobClient jobClient, ActivatedJob job, Throwable throwable) {
        //TODO
  }
}
```

* Inject DefaultCommandExceptionHandlingStrategy when missing bean
```
  @Bean
  @ConditionalOnMissingBean(CommandExceptionHandlingStrategy.class)
  public CommandExceptionHandlingStrategy commandExceptionHandlingStrategy() {
    return new DefaultCommandExceptionHandlingStrategy();
  }
```

> If the user provides a custom exception handling policy, the custom policy will be activated
```
public class CustomCommandExceptionHandlingStrategy implements CommandExceptionHandlingStrategy {

  @Override
  public void handleCommandError(JobClient jobClient, ActivatedJob job, Throwable throwable) {
  }
}
```

**Comment by berndruecker** [comment]
Hey @Lzgabel - this makes a lot of sense to me, we might also add a separate config property to select the strategy though. The idea was to experiment with a more sophisticated strategy, but not make this the default from the beginning. I wanted to start working on this after the merge of the ZeebeVariable and AutoComplete

**Comment by berndruecker** [comment]
@ConditionalOnMissingBean requires a new dependency to `spring-boot-autoconfigure` in spring-zeebe. Currently, spring-zeebe has no spring boot dependencies (only spring, spring boot is added in the spring-zeebe-starter project). So I wondered if that is a good idea to introduce - any opinion @Lzgabel ?

**Comment by Lzgabel** [comment]
Hi @berndruecker , maybe we can try this way? WDYT?

```
public class CommandExceptionHandlingStrategyRegistryPostProcessor implements BeanDefinitionRegistryPostProcessor, ApplicationContextAware {
  private ApplicationContext applicationContext;

  @Override
  public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
    this.applicationContext = applicationContext;
  }

  @Override
  public void postProcessBeanDefinitionRegistry(BeanDefinitionRegistry registry) throws BeansException {
  }

  @Override
  public void postProcessBeanFactory(ConfigurableListableBeanFactory beanFactory) throws BeansException {
    try {
      applicationContext.getBean(CommandExceptionHandlingStrategy.class);
    } catch (NoSuchBeanDefinitionException ignore) {
      CommandExceptionHandlingStrategy commandExceptionHandlingStrategy = new DefaultCommandExceptionHandlingStrategy();
      beanFactory.registerSingleton("commandExceptionHandlingStrategy", commandExceptionHandlingStrategy);
    }
  }
}
```

**Comment by berndruecker** [comment]
Thanks for the proposal - I am not sure if I come to work on this this year, but will take it into consideration 👍

**Comment by berndruecker** [comment]
Proposal:

- I close this for now
- I provide a default and add that to master successfully
- If somebody needs to extend it, we can look into this again having the real code in front of our eyes.

**Comment by berndruecker** [comment]
I looked into this again - as I need conditional beans for some other thing again. I think I found a really easy way to achieve this also with pure spring:

```java

  public static class OnMissingCommandExceptionHandlingStrategy implements Condition {
    @Override
    public boolean matches(ConditionContext context, AnnotatedTypeMetadata metadata) {
      return context.getBeanFactory().getBeanNamesForType(CommandExceptionHandlingStrategy.class).length<=0;
    }
  }

  @Bean
  @Conditional(value=OnMissingCommandExceptionHandlingStrategy.class)
  public DefaultCommandExceptionHandlingStrategy commandExceptionHandlingStrategy() {
    return new DefaultCommandExceptionHandlingStrategy(backoffSupplier(), scheduledExecutorService());
  }

```

@lzgabel WDYT?

**Comment by lzgabel** [comment]
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/24605947/203387132-4d647914-0dd2-43e5-a608-8e2556083bc3.png">


@berndruecker Thanks. ❤️  I tested it manually, and it works for me. 👍

**Comment by berndruecker** [comment]
Available on main - thanks for the quick response!
