### ISSUE TITLE
Feature Request: Inject custom headers as Map<String, String> in Handler Function

### ISSUE THREAD

**Issue by B-hamza** [camunda-community-hub/spring-zeebe#167]
As of ZeebeVariable and ZeebeVariablesAsType
This feature should enable the possibility to get headers injected :

``` java
@ZeebeWorker(type = "foo", autoComplete = true)
public void handleFoo(final ActivatedJob job, @ZeebeHeaders Map<String, String> headers){
  // do whatever you need to do
}
```

We could have both variables and headers combined as : 
``` java
@ZeebeWorker(type = "foo", autoComplete = true)
public ProcessVariables handleFoo(@ZeebeVariablesAsType ProcessVariables variables, @ZeebeHeaders Map<String, String> headers){
  // do whatever you need to do
  return variables;
}
```

**Comment by berndruecker** [comment]
Hey @B-hamza: I like the idea (even if it makes me wonder, if handing in just one proxy object providing all you need might actually be easier at some point in time). Would you be willing to create a pull request for this feature?

**Comment by berndruecker** [comment]
https://github.com/camunda-community-hub/spring-zeebe/pull/173
