### ISSUE TITLE
Feature Request: use jackson validation (jsr 303) when using @ZeebeVariablesAsType ?

### ISSUE THREAD

**Issue by B-hamza** [camunda-community-hub/spring-zeebe#193]
Now that we can use `@ZeebeVariablesAsType` it will be great if we can somehow use validation to validate our bean 
as example :
```java
@ZeebeWorker(type = "foo", autoComplete = true)
public ProcessVariables handleFoo(@ZeebeVariablesAsType **@Valid** ProcessVariables variables){
  // do whatever you need to do
  return variables;
}
```
Which can maybe trigger ZeebeBpmnError with the list of validation errors.

**Comment by B-hamza** [comment]
Yes, definitely it is a technical level exception indeed, thank you. 
I think **@Valid** needs the presence even of `jakarta.validation-api` or `spring-boot-validation` and the use of `Validation.buildDefaultValidatorFactory().validate(declaredbean)`
Then we can construct as you mentioned a runtime exception MethodArgumentNotValidException with the list of validation results ?

**Comment by berndruecker** [comment]
I wonder if we can find a way to make this work without baking it into spring-zeebe itself (sorry, being a bit reluctant to add stuff ;-)). As a workaround you can validate yourself WITHIN the worker by this line of code I guess - so this is also not a big pain.
