### ISSUE TITLE
Need to update yaml files for examples

### ISSUE THREAD

**Issue by superbeagle** [camunda-community-hub/spring-zeebe#197]
Examples use old yaml format:
zeebe:
  client:
    gateway.address: "127.0.0.1:26500"
    security.plaintext: true

Where it appears the newer versions add 'broker' and change **gateway.address** to **gateway-address**
zeebe.client.**broker**.gateway-address=127.0.0.1:26500
zeebe.client.security.plaintext=true

**Comment by berndruecker** [comment]
Thanks for reporting! I adjusted that according to the docs (and also simplified it a little bit - as I found some things confusing). 

I was even thinking if we should combine starter/worker into one app - as this is a common misunderstanding that you need one app per worker - so it might be better so simply have one Spring Boot App doing everything. WDYT @superbeagle?
