### ISSUE TITLE
Class "ProcessVariables" cannot be resolved

### ISSUE THREAD

**Issue by tobiasschaefer** [camunda-community-hub/spring-zeebe#202]
The class "ProcessVariables" cannot be resolved in the snippet from the README

```java
@ZeebeWorker(type = "foo", autoComplete = true)
public ProcessVariables handleFoo(@ZeebeVariablesAsType ProcessVariables variables){
  // do whatever you need to do
  variables.getMyAttribueX();
  variables.setMyAttribueY(42);
  // return variables object if something has changed, so the changes are submitted to Zeebe
  return variables;
}
```

I used the following dependencies:

```xml
<dependency>
	<groupId>io.camunda</groupId>
	<artifactId>spring-zeebe-starter</artifactId>
	<version>8.0.4</version>
</dependency>
<dependency>
	<groupId>io.camunda</groupId>
	<artifactId>spring-zeebe-test</artifactId>
	<version>8.0.4</version>
	<scope>test</scope>
</dependency>
```

So where does the class "ProcessVariables" come from or is the documentation simply not up-to-date?

**Comment by berndruecker** [comment]
Hi @tobiasschaefer.

The class "ProcessVariables" is a class you define yourself - and spring-zeebe will map the process variables into this. But I agree that this can be easily misunderstood by the docs - and I will do quick improvements on the readme.

Hope that helps?

Best
Bernd

**Comment by tobiasschaefer** [comment]
Hi @berndruecker , 

your renaming of the class name to `MyProcessVariables` made it much clearer. Thanks.

Cheers
Tobias
