### ISSUE TITLE
The default worker name property doesn't work

### ISSUE THREAD

**Issue by aivinog1** [camunda-community-hub/spring-zeebe#204]
So, I think the problem in this code:
https://github.com/camunda-community-hub/spring-zeebe/blob/master/client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/processor/ZeebeWorkerAnnotationProcessor.java#L81-L86
If the value isn't present we are setting the value from the class name and method name and not trying to set it from 
the `zeebe.client.worker.defaultName` property.

**Comment by berndruecker** [comment]
Good catch - will commit a fix now

**Comment by aivinog1** [comment]
Hey @berndruecker. 
I'm sorry but I think that there also problem in this code: https://github.com/camunda-community-hub/spring-zeebe/blob/b5d318cd4833ae356593d5bb61ca90a41e364a8d/client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/value/factory/ReadZeebeWorkerValue.java#L41-L43
So, I think, that we should remove this else condition and rely only on this part: https://github.com/camunda-community-hub/spring-zeebe/blob/b5d318cd4833ae356593d5bb61ca90a41e364a8d/client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/processor/ZeebeWorkerAnnotationProcessor.java#L81-L90
