### ISSUE TITLE
Custom JsonMapper not supported in @ZeebeSpringTest

### ISSUE THREAD

**Issue by mila973** [camunda-community-hub/spring-zeebe#215]
There is no option to configure ZeebeClient with custom JsonMapper when testing. ZeebeTestExecutionListener class creates client from test zeebe engine (embedded or container) method `.createClient()`, but no client configuration can be changed. 

This results in failing serialization in workers integration tests. `ZeebeClientProxy.class` can help, but only in test class not in worker bean.

It would be great to be able to use JsonMapper from application context bean.  

Used version of `spring-zeebe-test` = `8.0.6`

**Comment by berndruecker** [comment]
Hi @mila973 - thanks for reporting. This make sense to me spontaneously and can be added to the `ZeebeTestExecutionListener `

I wondered if there are other config properties we should also take into account for the ZeebeClient in testing from https://github.com/camunda-community-hub/spring-zeebe/blob/11966be454cc76f3966fb2c0e4114a35487946fc/client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/config/ZeebeClientStarterAutoConfiguration.java#L30, especially properties that are not related to the connection to Zeebe itself

-  builder.defaultJobWorkerName(configurationProperties.getDefaultJobWorkerName());
-  builder.defaultMessageTimeToLive(configurationProperties.getDefaultMessageTimeToLive());
- Listeners

WDYT?

**Comment by mila973** [comment]
Ideally, IMHO testing client should be as configurable as normal client (except for connection properties). At the moment JsonMapper is the only one that we need to tweak in our testing configuration.

**Comment by berndruecker** [comment]
Could you probably confirm that the change via https://github.com/camunda-community-hub/spring-zeebe/issues/215 would work for you? 

See https://github.com/camunda-community-hub/spring-zeebe/blob/master/test/common/src/main/java/io/camunda/zeebe/spring/test/AbstractZeebeTestExecutionListener.java#L42 - which would also be the basis to add other configs (I agree with your sentiment)

**Comment by mila973** [comment]
Yeah, this should help us. Thank you (Kudos for quick solution).

**Comment by berndruecker** [comment]
Released with 8.0.7 (you were lucky regards to timing as Zeebe Client 8.0.5 just got released :-))
