### ISSUE TITLE
Allow override of fetched variable for @ZeebeVariable annotation

### ISSUE THREAD

**Issue by derryx** [camunda-community-hub/spring-zeebe#218]
Currently the fetched variable name is derived from the name of the method parameter.

It would be nice to have something like this

```
public void workerMethod(@ZeebeVariable("nameToFetch") String someOtherName) {
...
}
```

which overrides the name of the fetched variable for this parameter.

**Comment by derryx** [comment]
It would help us to have the "nameToFetch" in a constant so that you cannot make an error with the variable naming. We think about using the @ZeebeVariablesAsType instead.

**Comment by berndruecker** [comment]
Thanks - helpful to know this thought!
I personally also think that a "VariableAsType" is a good alternative practice - which my colleagues in consulting also are using: https://github.com/camunda-community-hub/camunda-8-process-solution-template/blob/main/src/main/java/org/example/camunda/process/solution/worker/MyWorker.java#L20

**Comment by berndruecker** [comment]
@derryx I tend to close this for now unless you object?
