### ISSUE TITLE
How can i get a user task and complete it ?

### ISSUE THREAD

**Issue by odranoelBR** [camunda-community-hub/spring-zeebe#235]
My goal is, user fill an JS form and send to spring api. 
This api save data and finish the userTask.

I managed thought docs to add workers to handle service tasks, butt can't mannualy find userTask and complete it.
How can i fetch the current status with instance id ?

**Comment by jwulf** [comment]
From the [docs](https://docs.camunda.io/docs/next/components/modeler/bpmn/user-tasks/):

Alternatively, a job worker can subscribe to the job type `io.camunda.zeebe:userTask` to complete the job manually.

**Comment by jwulf** [comment]
So, you make sure that the Tasklist component is not running, and subscribe your worker to `io.camunda.zeebe:userTask`.
