### ISSUE TITLE
Rename annotations

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/spring-zeebe#239]
The annotations used in `spring-zeebe` will be renamed, according to our experiences using the library so far. We take the 8.1 release as a good moment in time to make that change. 
All existing annotations will be deprecated, but keep working for now (and will be removed in a future release).

`@ZeebeCustomHeaders` --> `@CustomHeaders`
`@ZeebeDeployment` --> `@Deployment`, already deprecated field `classPathResources` will be removed in the new annotation
`@ZeebeVariable` --> `@Variable`
`@ZeebeVariableAsType` --> `@VariableAsType`
`@ZeebeWorker` --> `@JobWorker`, **`autoComplete` default value** will be switched **from false to true** (as we see auto completion as the default to be used in most cases). `forceFetchAllVariables` got renamed to `fetchAllVariables`.

See also https://github.com/camunda-community-hub/spring-zeebe/pull/229 for some discussion on this issue

**Comment by berndruecker** [comment]
Todo: Adjust examples.

* https://github.com/camunda/camunda-platform-tutorials/blob/main/orchestrate-microservices/worker-java/src/main/java/io/camunda/getstarted/tutorial/Worker.java
* ...

**Comment by berndruecker** [comment]
@falko: Ping - it now exists on master

**Comment by bulivlad** [comment]
maybe a nice to have here would be a new field in `@ZeebeVariable` to specify the name of the variable to be retrieved. This way the variable name in code would not be tied with the flow variable

**Comment by berndruecker** [comment]
We discussed this in the past - and so far we decided against it - as I don't see a good reason why the Java variable name has to be different than the process variable name. Actually, it might even easily add confusion. Technically, there would not be a big show stopper though - but as this is an easy addition with a sensible default, we can still ad this whenever we want (whereas we wanted to have the renaming part of the 8.1 release)
