### ISSUE TITLE
Support Termination events

### ISSUE THREAD

**Issue by namero999** [camunda-community-hub/spring-zeebe#241]
With the release of Platform 8.1, Termination events are supported.

However, it is not clear how these events can be inserted via the BPMN programmatic API.

Compensation and Escalation, while not supported by the Platform, are exposed as methods by the API. Termination seems to be missing, or maybe it requires a different syntax since it's essentially and End event.

Can you provide an example?

**Comment by namero999** [comment]
The issue might be related to the fact that `io.camunda:spring-zeebe:8.0.11` still depends on `io.camunda:zeebe-client-java:8.0.7`. Will try to force the updated dep and see.

**Comment by namero999** [comment]
Confirmed to be a dependency problem, `terminate()` is present on `zeebe-client-java:8.1`. Probably will be automatically fixed by the 8.1 release of `spring-zeebe`.

**Comment by berndruecker** [comment]
There is already a spring-zeebe 8.1 release since yesterday (just saying :-))

**Comment by namero999** [comment]
Yep, today I can see it on maven central :) Thanks!
