### ISSUE TITLE
Adding `Operate API Java Client Factory` to Spring Zeebe

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/spring-zeebe#245]
There is a community based Operate API available: https://github.com/camunda-community-hub/camunda-operate-client-java

This needs to be configured / wired as it is for example done here: https://github.com/camunda/connector-sdk-inbound-webhook/blob/main/src/main/java/io/camunda/connector/inbound/operate/OperateClientFactory.java

This could be part of the spring-zeebe project if we assume that this is a common API being used.

**Comment by berndruecker** [comment]
@falko Do you have thoughts?

**Comment by berndruecker** [comment]
In order to move this over properly - we still need to figure out 

- how to enable/disable the client
- when exactly we want to connect to Operate (during startup? lazy?)
- What should happen if one can't connect

**Comment by zambrovski** [comment]
To me there should be several modules / artifacts in the library: zeebe client, operation client, task list client... and they all could be configured together to work in a Spring Boot environment by a single Spring Boot Starter...

**Comment by berndruecker** [comment]
See also: https://github.com/camunda-community-hub/camunda-operate-client-java/issues/14

**Comment by berndruecker** [comment]
Maybe tackled together with https://github.com/camunda-community-hub/spring-zeebe/issues/275

**Comment by berndruecker** [comment]
Operate can be auto-configured via Spring Zeebe in the meanwhile, see https://github.com/camunda-community-hub/spring-zeebe/blob/main/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/CamundaAutoConfiguration.java#L38 - so even if this integration could be probably improved I close this issue as I consider it done
