### ISSUE TITLE
"_" in secrets don't work in Spring environment

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/spring-zeebe#265]
>  It is probably because I use an underscore in MY_TOKEN, I think Spring will resolve this to MY.TOKEN... 

See https://camunda.slack.com/archives/C02JLRNQQ05/p1669060091198719

**Comment by McAlm** [comment]
It actually works, the problem was that the secrets have to be exposed to the runtime of SpringZeebe application, not to the Connectors docker image, e.g. by adding secrets to application.properties. It also works with underscore.
```
MY_TOKEN=palim
MYTOKEN=palam
```
