### ISSUE TITLE
Add metrics to Connector Runtime formerly written by the Cloud Bridge

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/spring-zeebe#268]
Splitted this into two parts:

- [x] Replace https://github.com/camunda/cloud-connector-bridge/blob/main/src/main/java/io/camunda/connectorbridge/invoker/ConnectorInvokerMetrics.java
- [x] Replace https://github.com/camunda/cloud-connector-bridge/blob/main/src/main/java/io/camunda/connectorbridge/zeebe/JobMetrics.java

Metrics are available via Spring Actuator on http://localhost:8080/actuator/metrics/:
* `camunda.connector.outbound.invocations`
* `camunda.connector.inbound.invocations`
* `camunda.job.invocations`

Work in: https://github.com/camunda-community-hub/spring-zeebe/pull/269

**Comment by berndruecker** [comment]
The Bridge metric layout [reuses the same counter for all different type of things (executed, failed, ...)](https://github.com/camunda/cloud-connector-bridge/blob/main/src/main/java/io/camunda/connectorbridge/invoker/ConnectorInvokerMetrics.java#L14-L19). Even if different tags are given, those just lead to a list of possible tags, see e.g. 

![grafik](https://user-images.githubusercontent.com/1217596/203730091-f6412754-5721-4f0c-9066-76155dddbfaa.png)

This is inline to what e.g. HTTP does as metrics:

![grafik](https://user-images.githubusercontent.com/1217596/203731002-fd05fcf6-61b9-49c0-9ac2-7142d4992161.png)

As the bridge only handled one connector, you got a number for its connector type from the bridge. The new runtime will handle multiple connectors, thus a counter per connector type makes more sense to me. I will add this to the name of the counter.

So
* camunda.connector.invocations.AWSLambda
* camunda.connector.invocations.HTTPJSON
* ...

![grafik](https://user-images.githubusercontent.com/1217596/203735337-f348ef1e-f61d-4c47-a418-b6b0546ff9a3.png)

**Comment by tmetzke** [comment]
Synced offline, results:
* We'll keep name to metric itself, not involve Connector name in there
* We'll use tags/labels as before in the Bridge
* We'll include job metrics in Spring Zeebe as well
* We'll create a Micrometer-based implementation in Spring Zeebe Starter, conditionally activated when Actuator is available
* We'll include Actuator in the Spring Zeebe Connector Runtime application

**Comment by berndruecker** [comment]
@igpetrov FYI - I also added basic metrics to the Webhook: https://github.com/camunda-community-hub/spring-zeebe/pull/269/commits/1f162a0903cba2a7f22396e8e604eb842ac37c98

**Comment by igpetrov** [comment]
@berndruecker 

Not sure how it is implemented exactly, should we have a separate thread pool for metrics? I am concerned that metrics can potentially exhaust execution threads.

**Comment by berndruecker** [comment]
This is handled by Spring Actuator automatically - same as with all other metrics collected (e.g. HTTP stats, memory, etc...). No need to worry I think

**Comment by berndruecker** [comment]
I struggled a bit with exchanging the MetricsRecorder and needed some digging on the weekend to find out the root problem - spring-zeebe is currently not using Spring Auto Configuration, see https://github.com/camunda-community-hub/spring-zeebe/issues/275. I have a workaround for the moment, so we are not blocked by this and I will merge this later today.
