### ISSUE TITLE
Add Javadoc to JobWorker annotation

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-community-hub/spring-zeebe#273]
## Description
The `@JobWorker` annotation provides a bunch of options that can be configured. These options are not all documented. It would help users if we provide some basic Javadoc for them.

On example which I've got questions about is for the `timeout`. It is unclear in which unit these should be defined. Javadoc could provide the extra context and explain that the timeout should be defined in milliseconds.

**Comment by berndruecker** [comment]
Great feedback @remcowesterhoud - thanks! Any chance you fancy a PR too add those? 
Otherwise I will try to have a look

**Comment by namero999** [comment]
Hello, since it was me opening the original issue on Slack, I've prepared the diff to include the JavaDocs, but creating the pull request is failing with a permission error. Do I need to be added to the repo in order to push PRs here?

**Comment by remcowesterhoud** [comment]
Hi @namero999!

You will have to fork this repository. You can then push your changes to your forked repo. Once that's done you can create a PR here and hit `compare across forks`. That will allow you to merge the changes of your forked repo into this one.

**Comment by namero999** [comment]
Apparently I've forgotten how to github properly. PR merged :) Can close.

**Comment by remcowesterhoud** [comment]
Thanks for the contribution @namero999 🙇
