### ISSUE TITLE
Doc update needed in 'Programmatically completing jobs' section

### ISSUE THREAD

**Issue by daniel-ewing** [camunda-community-hub/spring-zeebe#278]
[Programmatically completing jobs](https://github.com/camunda-community-hub/spring-zeebe#programmatically-completing-jobs) should specify setting `autoComplete = false` is required when programmatically completing jobs, otherwise a race condition occurs and the variables are not set about 35% of the time.  See reproducible scenario in [this branch](https://github.com/daniel-ewing/c8-basic-test/tree/worker-variable-not-saved).

**Comment by daniel-ewing** [comment]
@berndruecker, yes.  But it might take me a few days to get to it.

**Comment by daniel-ewing** [comment]
OK, done.

**Comment by berndruecker** [comment]
https://github.com/camunda-community-hub/spring-zeebe/pull/283
