### ISSUE TITLE
Unable to deploy YAML models?

### ISSUE THREAD

**Issue by tarazena** [camunda-community-hub/spring-zeebe#290]
Hi, Sorry for opening an issue for this, I didn't see discussions section here so I didn't know how to communicate it.

I'm following the documentation for [YAML Workflows](https://docs.camunda.io/docs/0.25/components/zeebe/yaml-workflows/) and I cant seem to deploy it via Java SDK, here is what im doing:
```kotlin
class Workflow {
    @Value("\${zeebe.client.broker.gateway-address}") val defaultAddress: String? = null

    @Bean
    fun deployWorkflow() {
        val clientBuilder = ZeebeClient.newClientBuilder().gatewayAddress(defaultAddress).usePlaintext();
        val client = clientBuilder.build()
        val fileContent = this::class.java.classLoader.getResource("app-intake-complete-automated.bpmn")?.readBytes()
        client
            .newDeployResourceCommand()
            .addResourceBytes(fileContent, "app-intake-complete-automated.bpmn")
            .send()
            .join();

        val fileContent2 = this::class.java.classLoader.getResource("order-process.yml")?.readBytes()
        client
            .newDeployResourceCommand()
            .addResourceBytes(fileContent2, "order-process.yml")
            .send()
            .join();
    }
}
``` 
Note that the `bmpn` file is getting deployed correctly, but when trying for the `yml` file, I get the following exception
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'deployWorkflow' defined in class path resource [com/test/camunda_poc/deployment/Workflow.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [void]: Factory method 'deployWorkflow' threw exception; nested exception is io.camunda.zeebe.client.api.command.ClientStatusException: Command 'CREATE' rejected with code 'INVALID_ARGUMENT': Expected to deploy new resources, but encountered the following errors:
2022-12-08 10:49:13 
2022-12-08 10:49:13 'order-process.yml': unknown resource type
2022-12-08 10:49:13     at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.24.jar!/:5.3.24]
...
```
`order-process.yml`
```yml
name: order

tasks:
  - id: retrieve-payment
    type: retrieve-payment-service

  - id: fetch-goods
    type: fetch-goods-service

  - id: ship-goods
    type: ship-goods-service
```

is yml file deployment not supported?

**Comment by lzgabel** [comment]
👋 Hi @tarazena. What version of the engine are you currently using? 

The support for YAML workflows was removed from the workflow engine, after the deprecation with 0.26. See here for details: [update-guide/026-to-100](https://docs.camunda.io/docs/1.0/guides/update-guide/026-to-100/#workflow-engine)

**Comment by tarazena** [comment]
I see, it wasn't clear to me that its not supported anymore because it was part of the earlier version documentation, Thank you so much.

**Comment by berndruecker** [comment]
Out of curiousity @tarazena: How did you exactly find the info about YAML (Google? ...?) and why was YAML interesting to you (not that there are any plans to reintroduce it  -still curious ;-))?  Thx

**Comment by tarazena** [comment]
We have some concerns about managing workflows in BPMN files and how to manage them in git, we were thinking managing workflows in YAML might be easier to read without rendering the diagram.

**Comment by berndruecker** [comment]
OK - thanks. I make a mental note that the yellow warning here seems to be not bold enough
![grafik](https://user-images.githubusercontent.com/1217596/208403760-306d4cfa-77f2-4487-bd24-596bc636906b.png)

That's said: BPMN XML in Git works relatively well for users (AFAIK) - so no worries. And BPMN is by far the more advanced language - so worth it!

Note that there are also diffing capabilities for BPMN (e.g. https://demo.bpmn.io/diff)
