### ISSUE TITLE
Allows to release alpha version

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/spring-zeebe#295]
We should be able to release proper alpha releases in the future (not sure if we can now)

**Comment by berndruecker** [comment]
@chillleader Do you know if we need to add anything to our pipelines / actions to be able to push the 8.2.0-alpha1? I can also simply try to do it whenever we have `main` ready for it

**Comment by chillleader** [comment]
@berndruecker it seems to me that in this case, we don't need anything specific.

**Comment by chillleader** [comment]
I'm going to go ahead and attempt the release. Maybe something comes up then.

**Comment by berndruecker** [comment]
Did work 🎉
