### ISSUE TITLE
Zeebe - Spring Boot compatibility 

### ISSUE THREAD

**Issue by bassgelo** [camunda-community-hub/spring-zeebe#309]
Question: 
Is there are a table where we could see the version compatibility between Zeebe and Spring Boot ?

Something like this one you already have for Camunda 7:
https://github.com/camunda/camunda-docs-manual/blob/master/content/user-guide/spring-boot-integration/version-compatibility.md

**Comment by berndruecker** [comment]
We have a very rudimentary table now: https://github.com/camunda-community-hub/spring-zeebe#version-compatibility
