### ISSUE TITLE
Custom grpc metadata

### ISSUE THREAD

**Issue by happwrap** [camunda-community-hub/spring-zeebe#314]
Hi! When calling the grpc-method "/gateway_protocol.Gateway/ActivateJobs" to the zeebe gateway, we need to add the task type to the metadata, for example: "job-type: http".
Based on what I managed to study, this function is not implemented. Is it possible to add this feature?
If I missed something, I would be grateful for tips on solving this problem.

**Comment by berndruecker** [comment]
The job type is used all over the place in spring-zeebe, see e.g. https://github.com/camunda-community-hub/spring-zeebe#implement-job-worker - or do I get the question wrong? What exactly do you try to achieve that is not working? Feel free to reopen this issue with details @happwrap
