### ISSUE TITLE
Suggestion to simplify working with simple types

### ISSUE THREAD

**Issue by Vladimir43543** [camunda-community-hub/spring-zeebe#316]
Hello. We use `spring-zeebe`, but extend it with additional annotations `JobArg`, `JobResult` for simplify working with simple types.

Maybe you want to have something similar?

It looks like this (kotlin):

```kotlin
  @UseAsZeebeWorker(type = "get-formatted-message-task-z")
  @JobResult("formattedMessageText")
  override fun getMessage(
    @JobArg("messageKey") messageKey: String
    @JobArg("format") format: String
  ): String {
      // body
      return formattedMessage;
  }
```

**Comment by berndruecker** [comment]
Why do you want to have a name in code that is different from a process variable name? This was discussed a couple of times in the past, and I still find this a source of confusion and haven't seen a really good use case for it ;-) 

I don't get what `JobArg` does exactly?

**Comment by namero999** [comment]
Is it possible to name a process variable with one of the reserved java keywords?

What if someone declares a process variable name `class`, and I can't control the BPMN generation but only write the worker?

In general I see the point of wanting to name process variable in a way but reference in code in some other way.

`@Variable("a-werid-name-someone-chose") String taskId`

**Comment by Vladimir43543** [comment]
> Why do you want to have a name in code that is different from a process variable name? This was discussed a couple of times in the past, and I still find this a source of confusion and haven't seen a really good use case for it ;-)
> 
> I don't get what `JobArg` does exactly?

  1. The json property name is the contract, it is ap part your API. You are unlikely to want to change the contract by accident (e.g. during automatic refactoring)
  2. `com.fasterxml.jackson` which is used to serialize  class objects allows setting specific json names (e.g. `@JsonProperty("MyCustomName"`) I guess it's good practice to do it the same way.


I also think it's useful to be able to set the name of the result returned by the worker, like `@JobResult("formattedMessage Text")`

**Comment by Vladimir43543** [comment]
> > Why do you want to have a name in code that is different from a process variable name? This was discussed a couple of times in the past, and I still find this a source of confusion and haven't seen a really good use case for it ;-)
> > I don't get what `JobArg` does exactly?
> 
> 1. The json property name is the contract, it is ap part your API. You are unlikely to want to change the contract by accident (e.g. during automatic refactoring)
> 2. `com.fasterxml.jackson` which _zeebe-cient_ uses to serialize  class objects allows setting specific json names (e.g. `@JsonProperty("MyCustomName"`) I guess it's good practice to do it the same way.
> 
> Yes our `@JobArg` it the same as `@Variable` only with a custom json name (we created it before the `@Variable` was added).
> 
> I also think it's useful to be able to set the name of the result returned by the worker, like `@JobResult("formattedMessage Text")`
@JsonProperty

It might even be better to use `@JsonProperty` instead of `@Variable`. But I'm not at all sure.

**Comment by jonathanlukas** [comment]
@Variable supports a variable name as parameter
