### ISSUE TITLE
Option to Dynamically Register JobWorker without annotations?

### ISSUE THREAD

**Issue by SaiprasadKrishnamurthy** [camunda-community-hub/spring-zeebe#324]
Hi , looking at the spring-zeebe project README and examples and I couldn’t find anything to dynamically create the JobWorker without the compile time annotations.

I’m trying to create a common library for Camunda/Zeebe where my services know nothing about the Workflow engine. It is pretty much agnostic and this library should take care of dynamically registering workers (specified by individual services) and the individual services just get a plain java call back with necessary payload and rest of the boiler plate is all handled by this common library.

I see this is only possible if there’s an alternative way to create job worker other than via @JobWorker annotation. Thoughts?

Kind of similar to Spring providing Dynamic registration mechanism to create Kafka Listener on the fly than @KafkaListener annotation.

**Comment by Curious-Eye** [comment]
I think you can autowire ZeebeClientLifecycle and use it's method "newWorker()" to dynamically register workers.

**Comment by berndruecker** [comment]
Hy @SaiprasadKrishnamurthy: You can register job workers via the JobWorkerManager, see how this is done internally after annotations are parsed: https://github.com/camunda-community-hub/spring-zeebe/blob/main/client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/annotation/processor/ZeebeWorkerAnnotationProcessor.java#L115

This should solve your problem - or not?
