### ISSUE TITLE
Support Interceptors from Beans

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/spring-zeebe#329]
Currently, `io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties` contains a field `interceptors` that is not connected to the spring context.

I would suggest to create an injection point where this field can be populated from Beans that implement this interface.

**Comment by berndruecker** [comment]
Out of curiosity: What is the use case where you need those interceptors @jonathanlukas?

Are you willing to provide a PR by chance?

**Comment by jonathanlukas** [comment]
I can do that. We are thinking about a way to enable `ExecutionListener` on Zeebe Jobs. They could be referenced as header containing a list potentially close a feature gap.

**Comment by berndruecker** [comment]
I can add a change to support this as part of https://github.com/camunda-community-hub/spring-zeebe/pull/363
