### ISSUE TITLE
Support inbound connector de-registration when diagram is undeployed

### ISSUE THREAD

**Issue by chillleader** [camunda-community-hub/spring-zeebe#337]
Soon Camunda 8 will provide an ability to undeploy the deployed diagrams. The runtime for inbound connectors does not support this action and, as of now, will simply ignore it and will not deactivate the corresponding connectors, if they are present in the deactivated diagram.

We need to support this scenario too and make sure all inbound connectors are deactivated when diagram is undeployed.

**Comment by berndruecker** [comment]
At the moment, it would de-active the connector upon restart - or? (as the process definition is gone then - or is the query still retrieving the process definition but in a disabled state?).

**Comment by chillleader** [comment]
Do you mean after the restart of the whole connectors application? It will be deactivated then, but I hardly see any value from this, especially when we consider subscription or polling connectors. I think we need to catch such occasions in runtime to deactivate in a timely manner.

**Comment by berndruecker** [comment]
Yeah - exactly. And I do agree that this is a useful feature, just not sure how high the priority is. But as restarting is nothing a user can trigger on SaaS - it is probably really not even a workaround - you are right...
Never mind - just thinking out loud ;-)

**Comment by jonathanlukas** [comment]
Moved to camunda/connectors
