### ISSUE TITLE
Reconcile identical inbound connectors in case of message events

### ISSUE THREAD

**Issue by chillleader** [camunda-community-hub/spring-zeebe#340]
### Description

Suppose the following diagram:

<img width="863" alt="Screenshot 2023-02-17 at 19 05 39" src="https://user-images.githubusercontent.com/38818382/219742402-0cc2e7f6-8676-40d1-a7a1-70f904b9f15f.png">

There are 2 types of behaviour I may have intended with this diagram:
- **Case 1:** `Payment succeeded` and `Payment failed` events come from different queues, and thus require different subscriptions
- **Case 2:** Both events come from the same queue and only require one subscription

We need to provide the user with a way to distinguish between these types of behaviour and support both cases in the Connector runtime. The current implementation only supports Case 1.

### Why support Case 2?

Consider an example:
I have a message queue with payment results. It can produce 2 types of messages:
1. `{"paymentId": "XXX", "status": "COMPLETED}`
2. `{"paymentId": "XXX", "status": "FAILED}`

If we only support Case 1, with the diagram above I will end up with 2 different consumers. Then I have to additionally worry about the following: How to make sure that each consumer reads only its own messages? This potentially increases the complexity of the Connector implementation and delegates the problem, which can be solved on the runtime level, to the user.

**Comment by chillleader** [comment]
Potential solution: add a new optional property called `Execution Key`
- Connectors with the same execution key will trigger only one subscription. At the same time, other properties of these connectors can be different, including `messageName` or `activationCondition`
- Connectors with different execution keys will trigger separate independent subscriptions
- If no execution key is specified, then this property receives a random value (i.e. separate subscriptions are created)

For those inbound connector types where this problem is irrelevant (for example, webhook, since it does not create any subscriptions) this property can simply be omitted in the element template.

**Comment by berndruecker** [comment]
I like the idea of having a sensible default and being able to overwrite it, if necessary. 
Spontaneously I thought about a property called `subscriptionSharingLabel` or the like - if this is the same - it will be shared. By default, own subscriptions are opened. WDYT?

**Comment by chillleader** [comment]
> Spontaneously I thought about a property called `subscriptionSharingLabel` or the like (but don't like `execution key`) - if this is the same - it will be shared. By default, own subscriptions are opened. WDYT?

How about `connectorInstanceId`? Or simply `deduplicationId` - this one should be intuitively clear without introducing any new concepts. I think that what I mentioned can also be applied to polling connectors, so I would ideally avoid explicitly referencing subscription.

At this point I don't want to introduce this property as something people can use in the Modeler, but I'd like to have this concept we discussed supported on the SDK/Runtime level to only handle the corner cases (like multiple connectors with the same message name) - and this will allow us to potentially support this as a feature later if it turns out to be needed by someone.

So I'd  just rename it in the [SDK](https://github.com/camunda/connector-sdk/blob/4dfd851f000645955ec2cb71ba6ec694dd28e047/core/src/main/java/io/camunda/connector/api/inbound/ProcessCorrelationPoint.java#L32) to whatever we agree on :)
