### ISSUE TITLE
Add an endpoint to return information about active webhooks for a diagram

### ISSUE THREAD

**Issue by nithinssabu** [camunda-community-hub/spring-zeebe#342]
### Context

We are tyring to enhance the UX for users modeling inbound webhook connectors in Web Modeler by [providing the Webhook URL ](https://github.com/camunda/web-modeler/issues/3335)the users can easily copy. Although the URL can be computed in Web Modeler itself using the following format,

`https://ConnectorURL/clusterId/inbound/webhookId`

Web Modeler doesn't know if the URL is really active.

### Description

Add an endpoint that will return the information about active webhooks for a given diagram based on the provided diagram id.

### Proposed solution

Web Modeler passes the diagram id to the endpoint and the responsse can be:

- Webhook ID, if the Webhook is active
- Empty, if the Webhook is not active

**Comment by chillleader** [comment]
Hi @nithinssabu, I drafted the API contract for this endpoint. Please let me know what you think about this.

### Request 
GET `${connectorsBaseUrl}/inbound`

Query parameters:
- `bpmnProcessId` - diagram id (optional parameter)
- `type` - connector type (optional parameter).

`type` parameter can be used to filter the running inbound connectors by type. Currently, we will only have one type of inbound connectors - `io.camunda:webhook:1`. But this will soon change, when we add support for e.g. RabbitMQ subscription or HTTP polling, which will require a similar UI feature in the Modeler.
Connector's `type` can be found in the element template JSON, and also in the process XML (but not sure if you have convenient access to it in the Modeler).

If no parameters are passed, then all active connectors will be returned - for all diagrams and all connector types.

### Response example

```
[
  {
    "bpmnProcessId": "8b1a3ac7-2edd-4d54-9c65-aa983c65edd8",
    "type": "io.camunda:webhook:1",
    "data": {
      "path": "/my-inbound-connector-path"
    },
    {
    "bpmnProcessId": "8b1a3ac7-2edd-4d54-9c65-aa983c65edd8",
    "type": "io.camunda:webhook:1",
    "data": {
      "path": "/my-other-inbound-connector-path"
    }
  }
]
```

**Comment by nithinssabu** [comment]
> Hi @nithinssabu, I drafted the API contract for this endpoint. Please let me know what you think about this.

Thanks for setting this up quickly, @chillleader. It looks good to me overall.

I have two things to clarify though:

1. The first parameter name is called `bpmnProcessId` but you expect the diagram id. Diagram id is what we see in the URL 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/5987816/220905224-700ca29b-6bdc-49f1-be22-46f9d2e52601.png">
and there is also the process id that we see in the properties panel and this is different
<img width="424" alt="image" src="https://user-images.githubusercontent.com/5987816/220905318-8ded3d1d-8ed4-40c5-a439-197bb4e8ac36.png">

If it's really the diagram id that you expect, then should we call the parameter `diagramId` to avoid confusion?

2. I do not see the `type` field [in the element template](https://github.com/camunda/web-modeler/blob/main/webapp/src/App/Pages/Diagram/BpmnJSExtensions/connectorsExtension/.camunda/element-templates/webhook-connector.json) but there is an `id` field that looks similar. Is this what you meant?

**Comment by chillleader** [comment]
1. I just clarified it: we actually use the `Process ID` from the properties panel that you show in the second screenshot. We have no access to the diagram ID in Connectors app - sorry for this confusion.
Is it possible for the Modeler to provide `Process ID`? I imagine it can be somewhat more difficult if there are multiple processes/participants in the diagram.

2. [This is what I meant](https://github.com/camunda-community-hub/spring-zeebe/blob/3ce23f293948c556a670f98eff703dfff19a88df/connector-runtime/element-templates/generic-webhook.json#L31) by the `type` field. In the template you're referring to, its currently just `webhook` (this value was set in the initial prototype), but it will be updated to `io.camunda:webhook:1` in the next release to match the same pattern for outbound connectors.

**Comment by nithinssabu** [comment]
> * I just clarified it: we actually use the `Process ID` from the properties panel that you show in the second screenshot. We have no access to the diagram ID in Connectors app - sorry for this confusion.
>   Is it possible for the Modeler to provide `Process ID`? I imagine it can be somewhat more difficult if there are multiple processes/participants in the diagram.

It is possible for Web Modeler to provide the `Process ID`.

> * [This is what I meant](https://github.com/camunda-community-hub/spring-zeebe/blob/3ce23f293948c556a670f98eff703dfff19a88df/connector-runtime/element-templates/generic-webhook.json#L31) by the `type` field. In the template you're referring to, its currently just `webhook` (this value was set in the initial prototype), but it will be updated to `io.camunda:webhook:1` in the next release to match the same pattern for outbound connectors.

Understood.

Everything is clear now and [the proposal](https://github.com/camunda-community-hub/spring-zeebe/issues/342#issuecomment-1440032215) looks good. Let's proceed with it. 👍

**Comment by nikku** [comment]
@chillleader @nithinssabu Does it also make sense to serve what led to the activation of a particular webhook (i.e. the deployment that triggered it)?

Use case: This could open a lot of possibilities to improve the UI on the web modeler site of things, i.e. we can track a deployment (that the user initiated) and poll for webhooks component to activate webhooks based on the last deployment we've seen. I may be wrong, of course.

**Comment by chillleader** [comment]
Sounds good @nikku.

From the Connectors perspective, we can only serve the process definition key (or business process ID + version) of the process definition that activated a connector.
However, per my understanding, it is not the same as deployment, since a diagram deployment may contain multiple process definitions.

**Comment by nithinssabu** [comment]
> @chillleader @nithinssabu Does it also make sense to serve what led to the activation of a particular webhook (i.e. the deployment that triggered it)?
> 
> Use case: This could open a lot of possibilities to improve the UI on the web modeler site of things, i.e. we can track a deployment (that the user initiated) and poll for webhooks component to activate webhooks based on the last deployment we've seen. I may be wrong, of course.

@nikku I do not fully understand what exactly you mean here. Can you please explain it in more detail?

**Comment by chillleader** [comment]
Thanks @nithinssabu. If you prefer continuous polling, I don't see any obstacles. Once the webhook is activated, it will immediately start to appear in the response.

**Comment by chillleader** [comment]
Follow-up: https://github.com/camunda/team-connectors/issues/356
