### ISSUE TITLE
Configuration properties in spring-zeebe differ from plain Java client

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/spring-zeebe#350]
I'm currently building another Zeebe Client for EJBs: https://github.com/camunda-community-hub/zeebe-ejb-client

Implementing the configuration in this new client, I found with pain that the configuration properties used in this (spring-zeebe) project are *not* aligned with the default configuration properties of the zeebe-java-client: [io.camunda.zeebe.client.ClientProperties](https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/ClientProperties.java)

Examples:

|  spring-zeebe | zeebe-java-client |
| ----------- | ------------- |
| zeebe.client.cloud.clientSecret | zeebe.client.cloud.secret |
| zeebe.client.broker.gateway-address | zeebe.client.gateway.address |

Two questions: 
1. Why did you choose different property names?
2. What should I do for the Zeebe-EJB-Client? 
    * Follow the spring-zeebe way? 
    * Keep the default (zeebe-java-client)? 
    * Define another pattern?

**Comment by jangalinski** [comment]
I cannot really remember making a _choice_ ... it was "In the early days" of zeebe with many changes in the API and a lot of configurations that had not been invented yet ... 

I guess consolidating the properties (probably on the java-client level) and applying the structure to spring and ejb seems fair ... but will be breaking.

**Comment by berndruecker** [comment]
I agree that it would be great to harmonize things - but we would need to do this in a backwards compatible way - which would probably mean to support both properties in spring-zeebe (and default to what the Java Client does). 

Did you investigate of there are more differences @ingorichtsmeier ?

**Comment by ingorichtsmeier** [comment]
I will have a closer look. It was at first very confusing for me, why my mix of copy-and-paste from spring zeebe and the ClientProperties didn't work.

I will do some Bugtracking on zeebe-java-client (region is not applied here) and then have a deeper look and list all differences.

After that, it could be a quick fix to read the values from several properties like `zeebe.client.broker.gateway-address` and `zeebe.client.gateway.address`, looking for the spring-zeebe properties first.

**Comment by ingorichtsmeier** [comment]
Here is the complete table from the relevant classes [`io.camunda.zeebe.client.ClientProperties`](https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/ClientProperties.java) and [`io.camunda.zeebe.spring.client.properties.ZeebeClientConfigurationProperties`](https://github.com/camunda-community-hub/spring-zeebe/blob/main/client/spring-zeebe-starter/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java).

| description | spring-zeebe | zeebe-java-client |
| ------ | ------ | ------ | 
| Gatway address | zeebe.client.brocker.gatewayAddress | zeebe.client.gateway.address |
| Use plaintext connection | zeebe.client.security.plaintext | zeebe.client.security.plaintext |
| Cloud cluster id | zeebe.client.cloud.clusterId | zeebe.client.cloud.clusterId |
| Cloud client id | zeebe.client.cloud.clientId | zeebe.client.cloud.clientId |
| Cloud client secret | zeebe.client.cloud.clientSecret | zeebe.client.cloud.secret |
| Cloud region | zeebe.client.cloud.region | zeebe.client.cloud.region |
| Job worker execution threads | zeebe.client.worker.threads | zeebe.client.worker.threads |
| Job worker max jobs active | zeebe.client.worker.maxJobsActive | zeebe.client.worker.maxJobsActive |
| Default job worker name | zeebe.client.worker.defaultName | zeebe.client.worker.name |
| Default job timeout | zeebe.client.job.timeout | zeebe.client.job.timeout |
| Default job pollintervall | zeebe.client.job.pollInterval | zeebe.client.job.pollinterval | 
| Default message time-to-live | zeebe.client.message.timeToLive | zeebe.client.message.timeToLive |
| Default request timeout | zeebe.client.requestTimeout | zeebe.client.requestTimeout |
| CA certificate path | zeebe.client.security.certPath | zeebe.client.security.certpath |
| Keep alive | zeebe.client.broker.keepAlive | zeebe.client.keepalive |
| Apply environment variables override | zeebe.client.worker.override (Map) | zeebe.client.applyEnvironmentVariableOverrides (Boolean) |

**Comment by berndruecker** [comment]
Ah - great - somehow related to changes I currently do with https://github.com/camunda-community-hub/spring-zeebe/pull/306/files maybe we could add this to 8.2 already :-)

**Comment by ingorichtsmeier** [comment]
It would be nice, if spring-zeebe also accepts the zeebe-java-client properties.

**Comment by berndruecker** [comment]
I agree and I think I can have a look at it this week. 
The lower/uppercase should not matter - but I think I can add a test case to verify this

**Comment by berndruecker** [comment]
Will add this as part of https://github.com/camunda-community-hub/spring-zeebe/pull/363

**Comment by berndruecker** [comment]
@ingorichtsmeier Maybe you can have a quick look at the referenced commits as quick review?

**Comment by ingorichtsmeier** [comment]
Hi @berndruecker,

thank you for taking over! 

Overall, it looks good. I left some comments on the commits to use constants instead of Strings. 

But it will work even without further changes.

**Comment by berndruecker** [comment]
Thanks Ingo! I imporved the code according to your comments: https://github.com/camunda-community-hub/spring-zeebe/commit/b243642286baf34b9beb1abd1e054656bc35a855
