### ISSUE TITLE
Beans with no no-args constructor prevents startup

### ISSUE THREAD

**Issue by brix-ag** [camunda-community-hub/spring-zeebe#351]
`OutboundConnectorManager` tries to load connectors and calls `OutboundRegistrationHelper::parse` which either tries to load the connectors from classpath or environment variables. However the connectors on the classpath are not only discovered, but it also tries to create an instance using the no-args constructor (just to later discover the connector already exists) and if that fails everything fails.

Two possible fixes, it basically comes down to the following question: do we have to be able to configure the connectors with beans and from classpath in combination? I think the answer is no, so I would go for 1.

1. First line in `OutboundConnectorManager::start`, just add `if (outboundConnectors.isEmpty())` to only load connectors from classpath and env if there was no bean defined.
2. Add additional field `clazz` to `OutboundConnectorConfiguration` and only populate this field and not `function` in the helper. So the manager can check whether it is a duplicate *first* and only then populating `function` and adding the connector. Otherwise useless instances are created just to be discarded later because they are duplicates (besides the error if there is no no-args constructor). Equals and hashcode only depend on `type`, so this should work fine.

**Comment by chillleader** [comment]
Is my understanding correct that you're overriding a connector already present in classpath by introducing a Spring bean connector for the same `type`?

In that case, you can use a custom Connector Runtime bundle that doesn't contain connectors you don't need. Please refer to [this example](https://github.com/camunda/connectors-bundle/blob/main/bundle/mvn/default-bundle/pom.xml) of a Maven-based bundle to build your own.

**Comment by brix-ag** [comment]
No I am running a custom connector runtime with custom connectors. The out-of-the-box connectors all have no-args constructors. Our connector beans just have a constructor generated by @RequiredArgsConstructor where everything is injected. Yes we can add a no-args constructor, add the required args constructor manually and mark it as Autowired, but that's not the point. I showed exactly where the problem is, what and why it is happening and even how to fix it. This is completely independent from our configuration.

**Comment by brix-ag** [comment]
What do I have to do to talk to a developer? Can I fix it myself? New branch and merge request? Or how does this work? I already opened a ticket at Camunda answered tons of questions until they sent me here and now here the same thing. I know what I am talking about, the configuration is not the problem! I would be glad to have such detailed bug reports. But it seems it is not worth the effort.

**Comment by brix-ag** [comment]
I analyzed your commit https://github.com/camunda-community-hub/spring-zeebe/commit/ff5a64d274de488084ca106b0b1b227b891e53b4 and changes for util.

I'm positive this is fixed now. Looks like you implemented both fixes, but in a more elaborate way.

**Comment by berndruecker** [comment]
So we can close this issue @brix-ag - right?
