### ISSUE TITLE
Prepare spring-zeebe to evolve towards a "camunda-8-spring-sdk"

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/spring-zeebe#367]
We want to develop spring-zeebe towards being the Camunda 8 Spring SDK (like the Node SDK: https://github.com/camunda-community-hub/camunda-8-sdk-node-js). Camunda-internal doc: https://docs.google.com/document/d/1W7VueAdUJgQoGxY1X_H_DJimSEX1hxT-JJjKfaBzrFY/edit

As a first step we can prepare the spring-zeebe project for that move:

- [x] Make sure all “Zeebe Client” logic is in its own sub module (based on https://github.com/camunda-community-hub/spring-zeebe/tree/main/client/spring-zeebe)
- [x] Add own sub module for other clients, starting with Operate, somehow based on [existing community extension](https://github.com/camunda-community-hub/camunda-operate-client-java)
- [x] Separate the “starter” application (Spring Auto Configuration) where you can configure everything and switch components on/off (e.g. you only want to connect to Zeebe, not Operate - or the other way round)
- [x] Extract connector runtime (https://github.com/camunda-community-hub/spring-zeebe/tree/main/connector-runtime) and move it to an own place (probably within https://github.com/camunda/connectors-bundle)
- [x] Add legacy warnings to old artifact names
- [x] Double check naming of configuration options
- [x] Adjust documentation and write update docs

Next steps will be:
- Rename Spring-Zeebe to Camunda 8 Spring SDK
- Add clients for Tasklist, Optimize, Console

**Comment by berndruecker** [comment]
Thinking about naming (of course) - current proposal: 

* Package: `io.camunda.zeebe.spring` (I would not touch this, as this would require too much changes for existing users)
* Maven GroupId: `io.camunda.spring` (I would adjust now as we are cleaning up and forcing people to adjust dependencies anyway)
* Maven ArtifactIds:
  * spring-base / common / util / ...? I think we will move some things out of zeebe-client (e.g. Metrics) as this could also be used for operate-client. Just naming 🤔 
  * spring-zeebe-client
  * spring-operate-client
  * spring-boot-starter-camunda
  * spring-boot-starter-camunda-test-common
  * spring-boot-starter-camunda-test
  * spring-boot-starter-camunda-test-testcontainer

We could keep some legacy dependencies:
```
  <groupId>io.camunda</groupId>
  <artifactId>spring-zeebe-starter</artifactId>
```
would simply pull in
```
  <groupId>io.camunda.spring</groupId>
  <artifactId>spring-boot-starter-camunda</artifactId>
```
So existing projects don't have to adjust right away. Maybe we just add one bean that dumps a big deprecation warning for those legacy dependencies.

**Comment by jonathanlukas** [comment]
Changes in package names and artefact ids can be breaking, as the whole structure changes. 
As package name, I would like your proposal:

`io.camunda.spring.boot` as base, followed by each component.

To have a good developer experience, we could "fade out" old artefacts, deprecating them (and all their content) and adding startup logs. They will still work, but not receive any new features.
---
Artefact Naming:

`spring` is not precise as we use `spring-boot`. All artefact names should reflect this:

`spring-boot-starter-camunda-client-zeebe`
`spring-boot-starter-camunda-client-operate`
`spring-boot-starter-camunda-client-tasklist`
`spring-boot-starter-camunda-client`
...
---
Proposal: Identity SDK, Cloud Auth SDK: `spring-boot-starter-camunda-client-auth`

As all clients will in the end use the same authentication provider during runtime, they can share one SDK to retrieve credentials from. The only thing that would change is the scope for which the token is retrieved.

All implementations that are part of the future `spring-boot-starter-camunda-client` come with their own authentication provider, yet they should be bound to one configuration to prevent double configuration.

**Comment by berndruecker** [comment]
Thx for the quick feedback!
Actually `spring-client-zeebe` is correct - as this part is Spring only - not Spring Boot. Only the starter module is Spring Boot.

I am not sure if `spring-camunda-client-zeebe` is better than `spring-client-zeebe` - it feels a bit unnecessary lenghty to me - WDYT @jonathanlukas

**Comment by ingorichtsmeier** [comment]
Side note about restructuring: When I started the zeebe-ejb-client I looked into the implementation of spring-zeebe's annotations, with the hope to reuse them. Some of the annotations are tightly coupled to Spring. @berndruecker, do you think it may be possible to refactor some of them to common Java implementations and extract them as well? 

They could be used in other frameworks (JavaEE/JakartaEE/Quarkus/...) afterwards.

Benefit: at least a basic common annotation support for all Java client libraries.

**Comment by akeller** [comment]
> To have a good developer experience, we could "fade out" old artefacts, deprecating them (and all their content) and adding startup logs. They will still work, but not receive any new features.

Big +1 here, and not just because of the developer experience reference 😉 

> I am not sure if spring-camunda-client-zeebe is better than spring-client-zeebe - it feels a bit unnecessary lenghty to me

I vote spring-client-zeebe. Camunda in this context is redundant. spring-client-* for each of the components.

**Comment by jonathanlukas** [comment]
Ok, but `spring-zeebe-starter` should become `spring-boot-starter-client-zeebe` then, without the `camunda` but with `spring-boot-starter`.

**Comment by jonathanlukas** [comment]
@berndruecker the `spring-boot-starter-camunda` will include clients for all Camunda 8 APIs I guess.

For community implementers, this means they will have "useless" clients. Would it make sense to provide a `spring-boot-starter-client-zeebe` or `spring-boot-starter-zeebe`?

**Comment by berndruecker** [comment]
You are correct, but I would not like to add more complexity just to save some dependencies which should not harm much in most situations. Because first of all, the client can be switched-off, yes, and second you could still exclude the dependency if it does harm for whatever reason. But I would consider that the special case for the moment. If it turns out to be a problem we could still add own starters that pull in only parts of the API more specifically.

In general I want to go for a "This is the Camunda SDK for Spring" feeling that does not make you think about too much of what different API's you might need or not need behind the scenes.

**Comment by berndruecker** [comment]
Work is in https://github.com/camunda-community-hub/spring-zeebe/issues/367

**Comment by berndruecker** [comment]
Step 1 done and merged https://github.com/camunda-community-hub/spring-zeebe/pull/369

```
[INFO] Reactor Summary for spring-client-root 8.2.0-alpha2-SNAPSHOT:
[INFO]
[INFO] spring-client-root ................................. SUCCESS [  0.597 s]
[INFO] spring-client-annotations .......................... SUCCESS [  0.747 s]
[INFO] spring-client-common ............................... SUCCESS [  0.297 s]
[INFO] spring-client-zeebe ................................ SUCCESS [  0.620 s]
[INFO] spring-boot-starter-camunda ........................ SUCCESS [  3.375 s]
[INFO] spring-boot-starter-camunda-test-common ............ SUCCESS [  1.340 s]
[INFO] spring-boot-starter-camunda-test ................... SUCCESS [  1.720 s]
[INFO] spring-boot-starter-camunda-test-testcontainer ..... SUCCESS [  1.372 s]
[INFO] spring-boot-starter-camunda-example ................ SUCCESS [  1.376 s]
[INFO] [legacy] spring-zeebe .............................. SUCCESS [  0.229 s]
[INFO] [legacy] spring-zeebe-starter ...................... SUCCESS [  0.523 s]
[INFO] [legacy] spring-zeebe-test ......................... SUCCESS [  0.248 s]
[INFO] [legacy] spring-zeebe-test-testcontainer ........... SUCCESS [  0.320 s]
[INFO] [legacy] spring-zeebe-legacy-artifacts ............. SUCCESS [  0.120 s]
[INFO] [to be moved] spring-zeebe-connector-runtime ....... SUCCESS [  8.684 s]
```

**Comment by berndruecker** [comment]
@chillleader I think 8.2.0 is ready from my end. I would wait for Java Client 8.2.0 to be released and release it then (and tackle changes in documentation next - probably by a prepared PR). Does that work with you? Any dependencies I should be aware of or anything that must go into 8.2.0?

**Comment by chillleader** [comment]
@berndruecker I think there will be a PR by @markfarkas-camunda soon that fixes some issues he revealed when migrating the Connectors bundle to Spring Boot 3.

The only thing from my end - I was planning to try moving the connector runtime into a different repo next week. But considering the upcoming holidays, not sure I will have enough capacity - maybe makes sense to postpone it until after 8.2.0.

**Comment by berndruecker** [comment]
I will close this issue and moved remaining work into https://github.com/camunda-community-hub/spring-zeebe/issues/412

**Comment by akeller** [comment]
@berndruecker can you close this out and move any remaining work?
