### ISSUE TITLE
Webhook Connector: Support verification challenges

### ISSUE THREAD

**Issue by chillleader** [camunda-community-hub/spring-zeebe#379]
## What do we need to do?

Support verification challenges in HTTP Webhook Connector.

The verification challenge aims to check whether the user has control over the webhook handler code by sending a request with a certain parameter. Webhook handler must reply with the same parameter value or perform some operation on it.

[Learn more about verification challenge](https://webhooks.fyi/security/one-time-verification-challenge)

## Breakdown

⚠️ Verification endpoints usually use GET requests - #386 is a prerequisite and a blocker for this issue.

- [ ] Analyse how one-time verification is handled in real-life integrations and define the implementation scope accordingly
  - Proposed more or less universal solution: require the user to provide a FEEL expression that transforms any part of incoming request. The result of this expression is returned in response body.
  - Presumably, verification challenges almost always use GET requests and imply that regular webhook requests use POST. Therefore, we can assume that verification challenges can only be configured when the overall webhook method is POST.
- [ ] Develop webhook element template changes to support verification challenge configuration, which may look something like this (depending on the implementation scope):<br><img width="384" alt="Screenshot 2023-03-30 at 12 55 02" src="https://user-images.githubusercontent.com/38818382/228814724-0633d455-065a-40e5-833d-b4b2399995c9.png">
- [ ] On top of the changes implemented in #386, support the one-time verification flow in connector runtime:
  - [ ] When verification challenge is enabled for a specific webhook, an additional GET webhook should be activated alongside the main POST webhook. This state should be stored in [`WebhookConnectorRegistry`](https://github.com/camunda-community-hub/spring-zeebe/blob/main/connector-runtime/src/main/java/io/camunda/connector/runtime/inbound/webhook/WebhookConnectorRegistry.java).
  - [ ] Verification challenge endpoint should always reply with a result of a FEEL expression evaluation. FEEL expression should be configurable in an element template.
  - [ ] When webhook is deactivated (e.g. new process definition is deployed without webhook connector), verification endpoint should be deactivated as well.

## Why should we do it?

In many API integrations, like Slack or Meta/Facebook, it is required to complete the verification challenge. Lack of its support is a major limitation for our ability to support various real-world systems.

**Comment by l646505418** [comment]
Hi, @chillleader ,I want to contribute some code to this repotory,so would you mind explaining the tasks more specifically?

**Comment by chillleader** [comment]
Hi @l646505418 👋 Thank you for your interest in contributing to spring-zeebe!

I added more context to clarify the expectations around this task. I also created #386 which is a blocker for this issue.
As you can see, we still haven't agreed on the solution here, and we need to further analyze how different webhook providers handle verification challenges, so our solution allows integration with the majority of providers.

We are currently intending to handle this task as part of our regular work in the Camunda Connectors team. But any inputs and contributions are welcome, of course.

P.S. If you are not interested specifically in this issue and are just looking for a good first task, there are better ones out there, in my opinion. For example, you can also look at https://github.com/camunda-community-hub/spring-zeebe/issues/325. And of course please reach out if you need more context around this or any other issue here 🙂

**Comment by chillleader** [comment]
This issue was transferred to the [connectors-bundle](https://github.com/camunda/connectors-bundle/issues/516) repo.
