### ISSUE TITLE
How to connector to zeebe gateway without config port

### ISSUE THREAD

**Issue by gogroup-official** [camunda-community-hub/spring-zeebe#385]
My zeebe gateway goes through a proxy and has an endpoint of zeebe.xxx.com/gateway.
by default zeebe node will insert port 26500 leading to connection failure.
`| zeebe |  [worker-1] ERROR: Grpc Stream Error: 14 UNAVAILABLE: Name resolution failed for target dns:zeebe.xxx.com/gateway:26500 - zeebe.xxx.com/gateway:26500`
Is there any solution to fix this?
i just want to configure hostname

**Comment by berndruecker** [comment]
If you want to have it on port 80 - wouldn't it work to configure: `zeebe.client.broker.gateway-address= zeebe.xxx.com:80`? Or am I missing something?
As 26500 is the default port, not specifying it would especially not work, as then it would be 26500 ;-) 
I would close this for now - let me know if there are more issues (probably best asked in the forum: https://forum.camunda.io/)!

**Comment by gogroup-official** [comment]
my endpoint has path so i can't add port behind endpoint

**Comment by berndruecker** [comment]
I haven't double checked if and how this is possible with grpc, but it does not look like this setup is possible with the existing Zeebe Java Client (which is used in the Spring integration): https://github.com/camunda/zeebe/blob/main/clients/java/src/main/java/io/camunda/zeebe/client/impl/ZeebeClientImpl.java#L125. 

Could you double check that this is generally a valid setup for gRPC?

**Comment by gogroup-official** [comment]
<img width="1738" alt="Screenshot 2023-03-31 at 17 28 08" src="https://user-images.githubusercontent.com/19627226/229096416-aa9fc1e4-096c-4969-ae28-2cb18f1ba131.png">

**Comment by gogroup-official** [comment]
<img width="567" alt="Screenshot 2023-03-31 at 17 37 16" src="https://user-images.githubusercontent.com/19627226/229098067-bf8cf666-b917-4d7b-ae3a-0e8f24ec8073.png">
i modified ingress using rewrite target and it worked
