### ISSUE TITLE
why do you use Zeebe

### ISSUE THREAD

**Issue by fizz12344321** [camunda-community-hub/spring-zeebe#390]
Hi, I am reading your project and I love this project
I have a question, why do you choose Zeebe in your project instead of others like Camunda, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Zeebe instead of your project instead of others like Camunda

**Comment by quangtd95** [comment]
please read Camunda's documentation here first 
https://docs.camunda.io/docs/components/

**Comment by quangtd95** [comment]
> Hi, I am reading your project and I love this project I have a question, why do you choose Zeebe in your project instead of others like Camunda, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Zeebe instead of your project instead of others like Camunda

please read Camunda's documentation here first
https://docs.camunda.io/docs/components/

**Comment by berndruecker** [comment]
For general questions please refer to the forum: https://forum.camunda.io/
