### ISSUE TITLE
@Variable annotation should has a property to specify process variable name.  

### ISSUE THREAD

**Issue by aoral-pcln** [camunda-community-hub/spring-zeebe#394]
@Variable annotation should has a property to specify process variable name.  

   @JobWorker(type = VALIDATE_WORKER_NAME)
  public void validateCustomerCancellation( @Variable Reservation reservation)

{ ...   }
Currently worker method argument name "reservation" is used to retrieve process variable "reservation". If argument name changes without changing the process variable name, reservation becomes null. 

Suggested solution : 

Add name property and update JobHandlerInvokingSpringBeans. 

@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface Variable

{   String name =  "";  // if name missing method argument name can still be used.  }
CLOSED
[Don't notify me](https://jira.camunda.com/servicedesk/customer/portal/1/SUPPORT-16331#)
Shared with

Ali Oral
Creator

Alexander Tyulmankov
Remove

Ali Oral
Remove

Dmitriy Kashtelyan
Remove

Jordan Saletan
Remove

Mona Gulati
Remove

John Flanagan
Remove

**Comment by namero999** [comment]
I think this is a very important feature to have

**Comment by jonathanlukas** [comment]
Is already implemented: https://github.com/camunda-community-hub/spring-zeebe/commit/d710facfd6222937b83ed7d59e96fc2cd50abda2
