### ISSUE TITLE
Support DMN Evaluation

### ISSUE THREAD

**Issue by jothikiruthika** [camunda-community-hub/spring-zeebe#398]
Evaluation of DMN via the Spring Boot client is not supported, even if I include the latest version ( 8.2.0-alpha5 ) of the java client explicitly in the POM.xml

The below line of code throws an exception - 

``` client.newEvaluateDecisionCommand()
.decisionId(“benchmark-decision”)
.variables(variables); 
```

```Receiver class io.camunda.zeebe.spring.client.lifecycle.ZeebeClientLifecycle does not define or inherit an implementation of the resolved method 'abstract io.camunda.zeebe.client.api.command.EvaluateDecisionCommandStep1 newEvaluateDecisionCommand()' of interface io.camunda.zeebe.client.ZeebeClient.```

**Comment by jonathanlukas** [comment]
Works with the latest version
