### ISSUE TITLE
Allow more than one SecretProvider

### ISSUE THREAD

**Issue by bulivlad** [camunda-community-hub/spring-zeebe#409]
We're looking to use as many out of the box connectors as we can and also trying to hard code as less configurations in the flow as it will make it hard to change configurations in the future.

We are currently using `SpringSecretProvider` for some values but there is also a need to get properties from other different sources/files not bounded to Spring context so we would need use multiple secrets providers.

The SecretHandler object should have a List<SecretProvider> instead of single SecretProvider and check with every provider in the list when it is getting the secrets.

As a workaround we created a new secret provider bean and marked it as `@Primary` to override the `SpringSecretProvider` and call different other providers to get secrets from different sources/files. 

A specific use-case is to use the `GraphQL` connector and retrieve the query from a static file placed in the `resources` folder, similar to what spring graphql client does https://docs.spring.io/spring-graphql/docs/current-SNAPSHOT/reference/html/#client.requests.document-source

This request is probably linked to [this one](https://github.com/camunda/connector-sdk/issues/425)

**Comment by sbuettner** [comment]
@bulivlad This has been implemented in the context https://github.com/camunda/connectors/pull/632
