### ISSUE TITLE
ZeebeSpringTest fails when using `spring-boot-starter-camunda-test-testcontainers`

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/spring-zeebe#411]
Hello, running the tests of the following repo fails:

https://github.com/camunda-community-hub/camunda-7-to-8-migration/tree/feature/converter/core/prepare-8.2/example/process-solution-migrated

The exception can be reviewed here:

https://github.com/camunda-community-hub/camunda-7-to-8-migration/actions/runs/4743410469/jobs/8422927613

**Comment by berndruecker** [comment]
To document the root problem, the same bean is created by two factory beans (one from 8.1.8, one from 8.2.0) as the factory was moved to another package

```
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'outboundConnectorManager' ...
factoryBeanName=io.camunda.zeebe.spring.client.configuration.ConnectorConfiguration
...
factoryBeanName=io.camunda.zeebe.spring.client.connector.ConnectorConfiguration
```

**Comment by jonathanlukas** [comment]
Hi @berndruecker , thank you for this very detailed explanation. Indeed, I have overseen the transitive dependency.

I will decouple the upgrade of the adapter from the examples.
