### ISSUE TITLE
Evolve spring-zeebe towards a "camunda-8-spring-sdk" 

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/spring-zeebe#412]
Follow ups of https://github.com/camunda-community-hub/spring-zeebe/issues/367:

- [ ] Extract connector runtime ([https://github.com/camunda-community-hub/spring-zeebe/tree/main/](https://github.com/camunda-community-hub/spring-zeebe/tree/main/connector-runtime)
- [ ] Rename Spring-Zeebe to Camunda 8 Spring SDK

Next steps will be:

- Add clients for Tasklist, Optimize, Console

**Comment by akeller** [comment]
Closing this issue based on the update here - https://camunda.com/blog/2024/03/streamlining-camunda-apis-zeebe-rest-api/

> The new Spring Zeebe SDK ([spring-boot-starter-camunda-sdk](https://github.com/camunda/camunda/tree/main/clients/spring-boot-starter-camunda-sdk)) will be released and fully supported to help you easily use the Zeebe Java Client in your Spring or Spring Boot projects. This SDK will start as a fork of the community-maintained [Spring Zeebe Client](https://github.com/camunda-community-hub/spring-zeebe). Later this year, we’ll expand the Spring Zeebe SDK to deliver a Camunda Spring SDK that, similar to the NodeJS SDK, will provide a unified experience for interacting with all Camunda APIs in Java Spring. We recommend migrating to the officially supported Spring Zeebe and Camunda Spring SDK.

> The new Spring Zeebe SDK and Zeebe Java client will support both the Zeebe gRPC API and the REST API of Zeebe, providing easy migration between protocols and easier development of client applications.
