### ISSUE TITLE
CVE issue in commons-collections:3.2.2

### ISSUE THREAD

**Issue by qihaiyan** [camunda-community-hub/spring-zeebe#414]
commons-collections:3.2.2 is used by commons-beanutils:1.9.4, declared at 29 line of pom.xml

CVE REPORT: https://devhub.checkmarx.com/cve-details/Cx78f40514-81ff/

**Comment by 1nb0und** [comment]
This CVE can be fixed by this [PR](https://github.com/camunda-community-hub/spring-zeebe/pull/484)
