### ISSUE TITLE
Relocated packages

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/spring-zeebe#428]
Hello,

building the client with `mvn clean verify` from a pom file using

```
  <dependencies>
    <dependency>
      <groupId>io.camunda</groupId>
      <artifactId>spring-zeebe-starter</artifactId>
      <version>8.2.0</version>
    </dependency>
  </dependencies>
```

I got the message:
```
[WARNING] The artifact io.camunda:spring-zeebe-starter:jar:8.2.0 has been relocated to io.camunda.spring:spring-boot-starter-camunda:jar:8.2.0
```

This change is not covered in the README.

Are there any plans to announce this officially with a hint to the older versions, or is it just forgotten?

Background: I'm building a base template for a Camunda 8 platform training and wondering how to proceed.

Thank you, Ingo

**Comment by berndruecker** [comment]
Hi Ingo. The readme should show the latest group and artifact id. I did not see a specific reason to add some warning here - as Maven gives the warning itself and it only applies to existing users (and also they are not forced to update).

I your template you should actually update the values. If you see an important need to add documentation please send a PR. Thank you!
