### ISSUE TITLE
An application with the camunda-starter and the connector-bundle tries to connect to Operate

### ISSUE THREAD

**Issue by saig0** [camunda-community-hub/spring-zeebe#429]
**Describe the bug**

I have a Spring Boot application that depends on the latest `spring-boot-starter-camunda` in version `8.2.1` and on the `connector-runtime-bundle`. 

Since version `0.19.0` of the `connector-runtime-bundle`, the Spring Boot application tries to connect to an Operate API. Since I don't run an Operate instance, the application fails on startup. I see no way to disable the Operate client.

In version `0.18.2` of the `connector-runtime-bundle`, the Spring Boot application doesn't connect to Operate and starts as expected.

**To Reproduce**

I created a simple repository to reproduce the issue here: https://github.com/saig0/camunda-connectors-operate-issue

**Expected behavior**
The Spring Boot application doesn't connect automatically to Operate.

Or, at least, I can disable the Operate client. 

**Environment (please complete the following information):**
 - `spring-boot-starter-camunda`: `8.2.1`
 - `connector-runtime-bundle`: `0.19.2`
 - `spring-boot`: `2.7.8`

**Additional context**
This issue affects [Zeebe-Play](https://github.com/camunda-community-hub/zeebe-play). We are not able to update to the latest connectors bundle.

From the perspective of Zeebe-Play, it would be useful to have the option to switch the implementation that connects to Operate. We want to use inbound connectors but provide a different source for the deployed processes than the Operate API, for example, by providing an interface for the process importer.

**Comment by saig0** [comment]
@chillleader is this issue related to #399?

**Comment by sbuettner** [comment]
Closed and linked as the runtime has been moved to the `connectors-bundle`: https://github.com/camunda/connectors-bundle/issues/588

**Comment by chillleader** [comment]
Hey @saig0, in the latest Connectors release we moved all Connectors functionality out of Spring Zeebe to our [mono repo](https://github.com/camunda/connectors-bundle). To add connectors (including Zeebe & Operate clients) as a spring boot starter, please use the following dependency from now on:
```
<dependency>
    <groupId>io.camunda.connector</groupId>
    <artifactId>spring-boot-starter-camunda-connectors</artifactId>
    <version>0.19.2</version>
</dependency>
```
When using this dependency, you can use the following combination of properties to disable operate connectivity:
```
camunda.connector.polling.enabled=false
operate.client.enabled=false
```
I saw you already tried it in your example, but I just tested it with the new spring boot starter and it works for me. I suspect that the issue in your example is that connectors configurations are now gone from the `spring-boot-starter-camunda` and properties are therefore not resolved.

**Comment by saig0** [comment]
@chillleader nice catch. :tada: 

I can confirm the workaround. :+1: I added an empty `application.properties` file next to the `application.yml` file. Then, the application starts and doesn't try connecting to Operate. :rocket:
