### ISSUE TITLE
Support testing User Tasks

### ISSUE THREAD

**Issue by AlexanderPruss** [camunda-community-hub/spring-zeebe#435]
It is currently prohibitively difficult to test code that uses the Tasklist API to query and compute user tasks. Currently, the only way to get access to user tasks with the In-Memory Zeebe client is to activate Jobs of type UserTask, but this activation is not idempotent and does not contain the information that queries to the TaskList API would. 

Goal: Create a concept that allows user tasks to be claimed and completed using spring zeebe test tools. 

Suggestion: Add helper functions for this end to Spring Zeebe.

**Comment by jonathanlukas** [comment]
This will be in scope of the new, officially supported camunda-test library
