### ISSUE TITLE
Interceptor for JobWorker Methods

### ISSUE THREAD

**Issue by criew** [camunda-community-hub/spring-zeebe#445]
Most of our processes have some standardized variables like "businessKey" or "correlationId".
We would like to have some kind of "interceptor" around methods annotated with @JobWorker where we can put some of those variables into the MDC.

Is there any possibility to do this? One option could be to write a `ZeebeWorkerValueCustomizer` which replaces the MethodInfo in `ZeebeWorkerValue` with some kind of proxy, but it does not feel great.

Maybe some kind of callback interface? 
Or even better define and throw some Spring Events when a Job ist executed?

**Comment by cbertoldi** [comment]
We used an aspect to solve this.

**Comment by TechMz** [comment]
> We used an aspect to solve this (e.g. org.aspectj.lang.annotation.Aspect).
> 
> @around("@annotation(YourAnnotation)")

Hey @cbertoldi, if you don't mind me asking. Does your implementation also include the JobClient and ActivatedJob in the JobWorker method? I can inject an object that wraps both of those, however JobClient and ActiviatedJob have to be present in the method signature.

What I want:

```
@JobWorker
@WrapperAnnotation
workerMethod(WrapperObject object)
```

What I have:
```
@JobWorker
@WrapperAnnotation
workerMethod(WrapperObject object, JobClient client, ActiviatedJob job)
```

Using `@Around("@annotation(WrapperAnnotation)")`

**Comment by cbertoldi** [comment]
Hi @TechMz, yes, the method signature is void method(JobClient client, ActivatedJob job). Why do you need this WrapperObject?
