### ISSUE TITLE
Check if Java Client Micrometer Metrics are picked up by spring-zeebe

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/spring-zeebe#472]
As I just learned the Java Client has added some metrics. We should check if that is pulled into spring-zeebe correctly

**Comment by npepinpe** [comment]
It has to be explicitly enabled, since it's an optional dependency. e.g.

```java
final PrometheusMeterRegistry prometheusRegistry = ...;
final JobWorkerMetrics metrics =
    JobWorkerMetrics.micrometer()
        .withMeterRegistry(prometheusRegistry)
        .withTags(Tags.of("workerName", "myCoolWorker", "jobType", jobType))
        .build();
```

**Comment by 1nb0und** [comment]
Here is a first cut [PR](https://github.com/camunda-community-hub/spring-zeebe/pull/486) for enabling java-client metrics

**Comment by 1nb0und** [comment]
Moving this to the next milestone after receiving feedback

**Comment by 1nb0und** [comment]
Metrics PR has been merged
