### ISSUE TITLE
Worker threads do not initiate parallel executions

### ISSUE THREAD

**Issue by nthed** [camunda-community-hub/spring-zeebe#493]
Following the discussion on https://github.com/camunda-community-hub/spring-zeebe/issues/424, we added micrometer in the classpath and the worker's thread pool size seems ok using the following:

- Zeebe broker : 8.2.13
- spring-boot-starter-camunda : 8.2.4
- Java : 17

However we notice the following behavior.
We create a process instance in which the first job invokes an external service which has internally a thread sleep of 30 seconds.
While waiting for the response from the external service we create additional process instances and we were expecting these jobs to be executed in parallel with the first. However it seems that they get executed (in parallel) but only after the first job has been executed.
It seems as if the jobs are fetched at a specific point in time, and if the current batch is executing then additional jobs that are created are not picked up, even though that the number of parallel threads allows such an action
This behavior severely impacts parallel job processing

**Comment by jonathanlukas** [comment]
This is related to a behaviour of the zeebe client: https://github.com/camunda/zeebe/blob/main/zeebe/clients/java/src/main/java/io/camunda/zeebe/client/impl/worker/JobWorkerImpl.java#L213-L216

To overcome this, you could enable job streaming: https://github.com/camunda-community-hub/spring-zeebe?tab=readme-ov-file#enable-job-streaming
