### ISSUE TITLE
spring-zeebe 8.3.1 still using zeebe version 8.3.0

### ISSUE THREAD

**Issue by mohammedJ** [camunda-community-hub/spring-zeebe#504]
snippet from spring-client-root-8.3.1.pom
```
<groupId>io.camunda.spring</groupId>
  <artifactId>spring-client-root</artifactId>
  <version>8.3.1</version>
  <packaging>pom</packaging>

  <properties>
    <zeebe.version>8.3.0</zeebe.version>
```

Shouldn't the zeebe.version property also change to 8.3.1?

**Comment by 1nb0und** [comment]
Patch versions on spring-zeebe and zeebe can live separately as both are mostly bugfixes. But yes ideally if there is a latest zeebe version we should use it. Feel free to raise a PR or we can update it soon.

**Comment by namero999** [comment]
Would it matter to fix it now given that it has been published to maven already? How long before 8.3.2?

**Comment by 1nb0und** [comment]
@namero999 @mohammedJ 

We wil jump straight to version 8.3.4 by tomorrow, that way all versions on `zeebe`, `spring-zeebe`, and `zeebe-process-test` are in sync.

**Comment by 1nb0und** [comment]
8.3.4 has been released. Spring-Zeebe and the the rest of Camunda products are now on same version. Closing this.
