### ISSUE TITLE
Work with Spring Boot 3.2

### ISSUE THREAD

**Issue by BalikhinLB** [camunda-community-hub/spring-zeebe#511]
The release of Spring Boot 3.2.0 is scheduled for November 23rd. In it, the class [LocalVariableTableParameterNameDiscoverer](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/LocalVariableTableParameterNameDiscoverer.html) will be removed. To ensure functionality, it is necessary to update the MethodInfo class, replacing LocalVariableTableParameterNameDiscoverer with [StandardReflectionParameterNameDiscoverer](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/StandardReflectionParameterNameDiscoverer.html). Additionally, to ensure successful operation, it is necessary to update the pom.xml file:
`
<plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.11.0</version>
          <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
            <compilerArgs>
              <arg>-parameters</arg>
            </compilerArgs>
          </configuration>
</plugin>
`
The task is not a big one, I could have done it myself. However, it seems that some permissions are needed to push the branch, I am currently getting a 403 error.

**Comment by berndruecker** [comment]
Can you create a Pull Request instead @BalikhinLB ?

**Comment by BalikhinLB** [comment]
I feel very embarrassed, I haven't contributed to open source yet. To make a pull request here, do I need to execute a fork? I don't have the option to pull the branch directly into the current repository?

**Comment by berndruecker** [comment]
No worries - the first time is always the most exciting one :-)
Yes - you need to fork the repo and do the changes in your fork (there you have all permissions). Then you have the option to create a PR from there. Typically you create a branch for each PR - but I don't think GitHub forces you to.
See also https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by BalikhinLB** [comment]
Ok, thx. I did it: [PR](https://github.com/camunda-community-hub/spring-zeebe/pull/512)
