### ISSUE TITLE
Issue with updating process variables

### ISSUE THREAD

**Issue by mohammedJ** [camunda-community-hub/spring-zeebe#540]
If a process is started with a predefined variable and then updated on some kind of exception, then the update is not reflecting at the end of the process.

This used to work with spring-zeebe 8.2.4 but after moving to 8.3.1 it's no longer working.

e.g 

```
ProcessInstanceResult processInstanceResult = zeebeClient.newCreateInstanceCommand()
                ...
                .variables(Map.of("processFailed", false))
                .withResult()
                ...
```

JobWorker:
```
Map<String, Object> variablesAsMap = activatedJob.getVariablesAsMap();
// on exception
variablesAsMap.put("processFailed", true);
jobClient.newCompleteCommand(activatedJob.getKey())
                .variables(variablesAsMap) 
                ...
```

Checking variable after process completed
```
Map<String, Object> result = processInstanceResult.getVariablesAsMap();
boolean processFailed = (boolean) result.get("processFailed");
BEFORE:
processFailed = true // as expected
AFTER:
processFailed = false // not expected
```

**Environment:**
- OS: Linux
- Deployment: Self Managed
- Spring-Zeebe Version: 8.2.4 working, 8.3.0 and 8.3.1 not working
- SpringBoot Version: 3.0.2

**Comment by mohammedJ** [comment]
Any insight into this?

**Comment by 1nb0und** [comment]
Hello @mohammedJ 
I'm afraid I won't be able to look at this issue till end of year due to other priorities. But I will keep this in mind for the next milestone
