### ISSUE TITLE
`zeebe.client.cloud.*` properties are not respected by `SaaSAuthentication`

### ISSUE THREAD

**Issue by chillleader** [camunda-community-hub/spring-zeebe#560]
**Describe the bug**

Camunda Connectors team uses [Zeebe client cloud properties](https://github.com/camunda-community-hub/spring-zeebe/blob/e582dbc0ad93e7e31de2cdfa9c7ce034c568f9d0/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/properties/ZeebeClientConfigurationProperties.java#L344) to connect to SaaS clusters in Camunda SaaS environments other than production. We provide custom `baseUrl` and `authUrl` to connect to a different SaaS environment.

In the 8.3.4.1 release, it seems that the only `Cloud` properties respected by SaaS auth mechanism are `clientId` and `clientSecret`, and the `authUrl` property is [hardcoded](https://github.com/camunda-community-hub/spring-zeebe/blob/17e1fc4d9109a46c8952f380755fa18b459e396b/camunda-sdk-java/java-common/src/main/java/io/camunda/common/auth/SaaSAuthentication.java#L47).

**To Reproduce**

- Run Spring Zeebe against a SaaS cluster with custom auth URL & base URL
- Observe the error

**Expected behavior**

Spring Zeebe is able to authenticate against Camunda 8 SaaS development envioronment.

**Log/Stacktrace**

```
: "Authenticating for OPERATE failed due to io.camunda.common.exception.SdkException: Failed to deserialize json '' to class 'class io.camunda.common.auth.TokenResponse'"
```

</p>
</details>

**Environment:**
- Spring-Zeebe Version: 8.3.4.1

**Comment by chillleader** [comment]
Another observation on this topic: **`zeebe.client.cloud.clientId` and `zeebe.client.cloud.clientSecret` are ignored**

- Connectors users usually configure their self-managed installations by copying the client credentials from the Console UI, and those only contain credentials for the Zeebe client
- With the new Operate client, the above Zeebe properties do not trigger Operate client creation and auth token request for Operate. Only `operate.client.clientId` and `operate.client.clientSecret` lead to the correct auth configuration.
- Connectors override the default Operate client creation rules to create the Operate client (see [here](https://github.com/camunda/connectors/blob/main/connector-runtime/spring-boot-starter-camunda-connectors/src/main/java/io/camunda/connector/runtime/InboundConnectorsAutoConfiguration.java)), but still invoke the default code from `OperateClientProdAutoConfiguration`. That leads to the following pre-conditions for Operate client instantiation logic:
  - Only Zeebe properties are provided by the user, so the default condition for Operate client creation is not triggered
  - Connectors nevertheless invoke the configuration method to create the Operate client based on other conditions relevant to Connectors logic
  - `CommonClientConfiguration` doesn't detect the need to prepare Operate client authentication due to missing `operate.client.*` properties
- **Outcome**: Operate client is created (due to config override in connectors) but authentication for it is not prepared. Therefore the client doesn't work correctly.
- Suggestion: Modify the `CommonClientConfiguration` logic, so it prepares Operate auth config based on `zeebe.client.cloud.clientId` and `.secret` properties.

Note that Operate client doesn't throw any exceptions but continues to work in an inconsistent state. For example, calling the `searchProcessDefinitionResults` on such a misconfigured client results in a valid response (`ProcessDefinitionResult`), but all nested values of this DTO are nulls.

**How to reproduce this scenario?**

- Run the Connectors project using the [`LocalConnectorRuntime`](https://github.com/camunda/connectors/blob/main/bundle/default-bundle/src/test/java/io/camunda/connector/runtime/app/LocalConnectorRuntime.java) class
- Provide the following configuration in `application.properties`:

```
zeebe.client.cloud.region=<region>
zeebe.client.cloud.clusterId=<clusterId>
zeebe.client.cloud.clientId=<clientId>
zeebe.client.cloud.clientSecret=<clientSecret>
logging.level.io.camunda.operate=TRACE
logging.level.io.camunda.connector=TRACE
```
- Observe the following log statements: `Query process deployments...`. That indicates that Connectors code is successfully calling the Operate client, however, if you deploy a new process definition in that cluster, it is never detected.

**Comment by 1nb0und** [comment]
This [PR](https://github.com/camunda-community-hub/spring-zeebe/pull/573) should address the issue.

**Comment by 1nb0und** [comment]
And a [fix](https://github.com/camunda-community-hub/spring-zeebe/pull/578) for simple authentication (supa basic mode)

Closing this PR as resolved.
