### ISSUE TITLE
Camunda Operate client documentation

### ISSUE THREAD

**Issue by chDame** [camunda-community-hub/spring-zeebe#575]
**README**

Hi @1nb0und,

That would be really nice that the [java-client-operate](https://github.com/camunda-community-hub/spring-zeebe/tree/main/camunda-sdk-java/java-client-operate) would have its own documentation in case it is used outside of the spring zeebe client. We have some customers who could use it without integrating with Zeebe.

I'll wait for that documentation to archive the community operate client and point it here.

Thanks!

**Comment by chDame** [comment]
https://github.com/camunda-community-hub/spring-zeebe/pull/579

**Comment by sbuettner** [comment]
@chDame I assume this one is fixed as the PR you referenced has been merged?
