### ISSUE TITLE
Disable worker by the properties file does not work

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda-community-hub/spring-zeebe#627]
**Describe the bug**

According to the documentation https://github.com/camunda-community-hub/spring-zeebe/blob/main/README.md#disable-worker, it is possible to deactivate a worker via the properties file.

But this method does not work

**To Reproduce**

Create a worker
 @JobWorker(type = "incidentTask")
  public void createIncident(final JobClient client, final ActivatedJob job) {

Disable it by the properties file
zeebe.client.worker.override.incidentTask.enabled=false

Link the code 
<dependency>
      <groupId>io.camunda.spring</groupId>
      <artifactId>spring-boot-starter-camunda</artifactId>
      <version>8.2.4</version>
    </dependency>
  </dependencies>

Start the application: the worker should not start

**Expected behavior**

The worker should not start

**Log/Stacktrace**

**Environment:**
- OS: Whatever
- Deployment: worker is deployed on Self Manage. Server can be SM or SaaS
- Spring-Zeebe Version:  8.2.4
- SpringBoot Version: 2.7.7
- Configuration:

**Comment by jonathanlukas** [comment]
I can confirm that in version `8.2.4`, the merging of properties does not work, so disabling the worker via properties override has no effect.

However, in the latest version of the project, it DOES work, so 8.4.1 will definitely contain the fix. Is this sufficient?
