### ISSUE TITLE
zeebeTestEngine.increaseTime not working reliably for Spring Boot Tests 

### ISSUE THREAD

**Issue by tobiasschaefer** [camunda-community-hub/spring-zeebe#659]
**Describe the bug**

I have a process test whose process includes an timer intermediate catch event with a duration of 15 minutes. Obviously, I don’t want the test to wait but want be be able to trigger the timer (or rather increase the time of the environment so that it fires).

Here is a nice working example which works: [TimerTest.java 1](https://github.com/camunda-community-hub/camunda-8-examples/blob/929e8b6f88e69fd30df5a24650b4d9478a3bb29b/timer-testing/src/test/java/com/camunda/consulting/TimerTest.java)

However, this previous example uses `@ZeebeProcessTest` and in my case I have
`@SpringBootTest @ZeebeSpringTest` and it doesn’t work reliably.

To reproduce the issue I created a fork of the Camunda 8 Twitter Example: [twitter-with-timer 2](https://github.com/tobiasschaefer/camunda-8-examples/tree/twitter-with-timer) in which I

* added a timer with a duration in the process model
* added the same skipTimer implementation.
* disabled all tests but the first (to make it simpler)
* I replaced `@Test` with `@RepeatedTest(10)` to make the error more obvious and reproducible.

However, this test
* sometimes fails on the first zeebeTestEngine.waitForIdleState(DEFAULT)
* sometimes on the last zeebeTestEngine.waitForIdleState(DEFAULT)
* sometimes it succeeds.

See also discussion in the [forum thread #50258](https://forum.camunda.io/t/zeebetestengine-increasetime-not-working-reliably-for-spring-boot-tests/50258/4)

**Expected behavior**

Test should pass every time.

**Log/Stacktrace**

![image](https://github.com/camunda-community-hub/spring-zeebe/assets/5685151/90d66f18-668d-47ed-8b1e-9a0234689e5f)

Repetition 1: failed on “zeebeTestEngine.waitForIdleState(DEFAULT);” (first line in method skipTimeout) with a timeout

Repetition 2: failed a few lines later on
“zeebeTestEngine.waitForIdleState(DEFAULT);” (last (!) line in method skipTimeout) with a timeout

Repetition 4 failed with “Mockito.verify(twitterService).tweet(“Hello world”);”

On the second invocation all 10 were successful:

![image](https://github.com/camunda-community-hub/spring-zeebe/assets/5685151/80ab87e6-d552-4823-bae7-c8fa25629c4a)

On further invocations I get random results similar to the first and second invocation.

Note that the duration is quite different. I don’t know much about Zeebe internals but is there some configuration which can be set to make the timers being checked more often?

**Environment:**
- OS: Windows
- Deployment: none - its a local test with `@ZeebeSpringTest`, i.e. it uses the embedded process engine
- Spring-Zeebe Version: 8.3.1
- SpringBoot Version: 3.1.5
- Configuration: n.A.

**Comment by rshamborovskyy** [comment]
Same problem here. `@ZeebeSpringTest` with timer event and `increaseTime` passes randomly.
Would really like to have this one sorted out. Meanwhile I need to think about some workaround.

**Comment by tobiasschaefer** [comment]
Hi @jonathanlukas ,

this issue still affects us and Roman has the same issue. Since you were involved in the forum discussion before I created this issue and know who could support internally at Camunda:

Could you please get someone involved in this ticket so it gets fixed?

Best,
Tobias

**Comment by jonathanlukas** [comment]
@tobiasschaefer I investigated the problem today and had some findings. I am currently checking with the zeebe team.

**Comment by jonathanlukas** [comment]
@tobiasschaefer I just released a fixed version of the timer testing with additional working spring zeebe tests:

https://github.com/camunda-community-hub/camunda-8-examples/pull/376

**Comment by tobiasschaefer** [comment]
Hi @jonathanlukas ,

thanks a lot! 💯 

It's now working for me too 👍

**Comment by jonathanlukas** [comment]
Awesome! Now I just need to add something to the testing docs so that other people will not face the same issue. Do you have a proposal for that?

In detail, the problem is that `waitForBusyState` is also triggered by job activation.
