### ISSUE TITLE
Getting all users from Zeebe/Operate/Tasklist

### ISSUE THREAD

**Issue by michals96** [camunda-community-hub/spring-zeebe#668]
Hey guys,

quick question. Is there any way to fetch list of all currently available users in  Zeebe/Operate/Tasklist?

If not - is it on the roadmap? Do you have any suggestions how to introduce this feature?

It's rather critical to my project, I could even get my hands dirty with this feature and prepare a nice contribution :) 

Thanks a have a great day.

**Comment by michals96** [comment]
so there is no way to hit any api to get all users that operate/tasklist/zeebe already recognizes? (ie all users that already are available in elasticsearch)?

**Comment by jonathanlukas** [comment]
Hello @michals96 , 

es does not contain any user information. 
One exception is the dev setup without identity which is not designed for any other setup

**Comment by michals96** [comment]
Hey @jonathanlukas , what about the indices in elasticsearch like `operate-user` , `tasklist-user` ? I can see some user data there - but perhaps it is for internal use of specific tools :)

Example tasklist user record:
```
{
                "_index": "tasklist-user-1.4.0_",
                "_type": "_doc",
                "_id": "demo",
                "_score": 1.0,
                "_source": {
                    "id": "demo",
                    "userId": "demo",
                    "password": "$2a$10$n83i258cbD.UJt6OaxzzduLpztGm5XJlrEVZHwXcNiClXjwf2dF.O",
                    "displayName": "demo",
                    "roles": [
                        "OWNER"
                    ]
                }
            }
```

Example operate user record:

```
{
                "_index": "operate-user-1.2.0_",
                "_type": "_doc",
                "_id": "demo",
                "_score": 1.0,
                "_source": {
                    "id": "demo",
                    "userId": "demo",
                    "displayName": "demo",
                    "password": "$2a$10$qScIze2s4zIEiA.KFFRnzOG3MCgUZKUxIWpFGQ47hKnlV6yaYy0qO",
                    "roles": [
                        "OWNER"
                    ]
                }
            }
```

But of coruse it also might by just my dev setup :) 

Perhaps then such feature has to be introduced indivudally with regards for the authentication tool being used.

**Comment by jonathanlukas** [comment]
Hello @michals96 ,

they are only used for dev setups (without identity). 

For production, all user-related information is managed by identity.

**Comment by michals96** [comment]
Ok, this sounds good.

Thank you for your help @jonathanlukas ! :)
