### ISSUE TITLE
java-common has a dependency to identity-sdk that is not available in maven central 

### ISSUE THREAD

**Issue by chDame** [camunda-community-hub/spring-zeebe#684]
**Describe the bug**

I'm maintaining the java tasklient client that relies on the java-common from this project :
io.camunda.spring:java-common:8.4.0

When I update that dependency to a newer version (from 8.4.1 to latest), this has a dependency to identity-sdk in its pom :
<dependency>
<groupId>io.camunda</groupId>
<artifactId>identity-sdk</artifactId>
</dependency>

But this one is not present in maven central and it leads to compilation error
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find io.camunda:identity-sdk:8.4.3.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/io/camunda/identity-sdk/8.4.3/identity-sdk-8.4.3.pom
     Required by:
         project : > io.camunda.spring:java-common:8.4.2

**Comment by ManuelDittmar** [comment]
faced the same issue

**Comment by benno-huber** [comment]
regarding current version 8.5.0-rc2 there is a similar issue: now version 8.4.5 of io.camunda:identity-sdk is missing. Are those packages hosted by some private camunda repositories?

**Comment by benno-huber** [comment]
Issue possibly could be closed; you can find missing dependencies at camunda repository:
https://artifacts.camunda.com/ui/native/camunda-identity/io/camunda/identity-sdk/
On the other hand, it would be a good idea, to hold a copy at a common public maven repo.

**Comment by namero999** [comment]
Tagging @akeller as we had a quick exchange on another issue. This is less of a problem of the community-maintained spring-zeebe, and more of the Camunda Identity SDK not being published to the public maven repo. Is there a reason why it has not being pushed, or it has been pulled out? Upgrades from 8.4.2 upwards are made more difficult because of this.

**Comment by keuss** [comment]
Hi, any update ?

**Comment by namero999** [comment]
Ref: https://github.com/camunda-community-hub/spring-zeebe/issues/669#issuecomment-2066784585

**Comment by keuss** [comment]
Hi,
I will test. But we are still in camunda 8.4.
Is this a problem ?
