### ISSUE TITLE
Doc for enabling the Camunda Operate Client

### ISSUE THREAD

**Issue by francav** [camunda-community-hub/spring-zeebe#686]
**Description**

Missing information for configuring the properties necessary to enable the Camunda Operate Client

**Missing Properties:**
- `camunda.operate.client.url`
- `camunda.operate.client.username`
- `camunda.operate.client.password`

**Proposed Solution:**
Include the info into Connect to Zeebe section

**Comment by jonathanlukas** [comment]
With 8.5, the configuration got refactored. Now, the structure of the properties is clean and documented.

**Comment by francav** [comment]
Thanks @jonathanlukas
