### ISSUE TITLE
spring-boot-starter-camunda-test need jdk 21 instead 17

### ISSUE THREAD

**Issue by NFehringVHV** [camunda-community-hub/spring-zeebe#687]
**Describe the bug**

https://github.com/camunda-community-hub/spring-zeebe/blob/main/test/embedded/pom.xml

use java version 21 instead 17

**To Reproduce**

`<dependency>
<groupId>io.camunda.spring</groupId>
<artifactId>spring-boot-starter-camunda-test</artifactId>
<scope>test</scope>
<version>8.4.0</version>
</dependency>`

`
@SpringBootTest
@ZeebeSpringTest
public class ZeebeCoreAppTest {

...`

**Expected behavior**

No Exception

**Log/Stacktrace**

```
[ERROR] /..../ZeebeCoreAppTest.java:[9,36] cannot access io.camunda.zeebe.spring.test.ZeebeSpringTest
  bad class file: ..../ZeebeSpringTest.class)
    class file has wrong version 65.0, should be 61.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Environment:**
- OS: Windows
- Deployment: -
- Spring-Zeebe Version: 8.4.0
- SpringBoot Version: 3.2.2
- Configuration: -

**Comment by jonathanlukas** [comment]
This is not a bug. Zeebe requires java 21 from 8.4: https://github.com/camunda/zeebe-process-test

**Comment by NFehringVHV** [comment]
ok, good to know, then please fix the https://github.com/camunda-community-hub/spring-zeebe#version-compatibility :)
