### ISSUE TITLE
 [C8] Default Worker Property "autoComplete = true" contradicts Best Practies

### ISSUE THREAD

**Issue by geroe1** [camunda-community-hub/spring-zeebe#749]
**Describe the bug**

What are the steps to reproduce your problem?

    https://docs.camunda.io/docs/components/best-practices/development/writing-good-workers/#recommendation

    In jedem unserer Worker werden RemoteCalls gemacht. 

     

    Der empfohlene Einsatz von Reactive Programming führt dazu, dass sämtlicher Code, welcher die GRPC-Aufrufe (CompleteJob, FailJob, ThrowError) kapselt, unnötig ist.

        https://github.com/camunda-community-hub/spring-zeebe/blob/8.3.5/spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/JobHandlerInvokingSpringBeans.java#L46-L84
        https://github.com/camunda/zeebe/blob/8.3.5/clients/java/src/main/java/io/camunda/zeebe/client/impl/worker/JobRunnableFactoryImpl.java#L43-L64

    Durch den Default (autoComplete = true) führt das auch zu Fehlerpotential:

        Methode / REST-Call wird asynchron ausgeführt.
        CompleteCommand wird somit sofort an die Engine geschickt
        Sollte es nun zu einem Fehler kommen, dnan wird der Callback-Code ein FailCommand schicken. Dieses wird aber nicht mehr verareitet werden, da ja bereits ein CompleteCommand geschickt wurde

    Es wird in der Doku erwähnt (https://github.com/camunda-community-hub/spring-zeebe/?tab=readme-ov-file#programmatically-completing-jobs), allerdings halte ich den Default für riskant. Insbesondere da so gut wie jeder Worker (zumindest bei uns) Remote-Calls ausführt.

**To Reproduce**

see Bug Description above

**Expected behavior**

Workers shouldn't be autoComplete, since most of them are doing remote calls.

**Log/Stacktrace**
-

**Environment:**
- OS: Linux
- Deployment:SM (Self Managed) 
- Spring-Zeebe Version: 
- SpringBoot Version:  
- Configuration:

**Comment by jonathanlukas** [comment]
You can override the default behaviour by setting:

```yaml
camunda:
  client:
    zeebe:
      defaults:
        auto-complete: false
```
