### ISSUE TITLE
"Unable to determine authentication. Please check your configuration" Error on springboot application start up using spring-zeebe

### ISSUE THREAD

**Issue by mugdhavarpe** [camunda-community-hub/spring-zeebe#751]
**Describe the bug**

We have a self-managed C8 setup which we have upgraded to 8.4 version. Just standing up zeebe gateway and brokers. Not using identity, operate or any of the other servies.

When trying to update the spring-boot-starter-camunda to 8.4.2 and zeebe-client-java to 8.4.5 , getting error message at application start up -

2024-04-05T13:31:05.596-04:00  INFO 6241 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-04-05T13:31:05.613-04:00  INFO 6241 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-04-05T13:31:05.613-04:00  INFO 6241 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.19]
2024-04-05T13:31:05.664-04:00  INFO 6241 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-04-05T13:31:05.664-04:00  INFO 6241 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1742 ms
**2024-04-05T13:31:06.257-04:00 ERROR 6241 --- [           main] i.c.c.auth.DefaultNoopAuthentication     : Unable to determine authentication. Please check your configuration**
2024-04-05T13:31:06.262-04:00  INFO 6241 --- [           main] z.s.c.c.ZeebeClientProdAutoConfiguration : Creating ZeebeClient using ZeebeClientConfiguration [io.camunda.zeebe.spring.client.configuration.ZeebeClientConfiguration@31b6fb14]

Additional details - https://forum.camunda.io/t/camunda-8-upgrade-8-2-8-4/51264

**To Reproduce**

Import  the below dependency in a java spring application -
       <dependency>
            <groupId>io.camunda.spring</groupId>
            <artifactId>spring-boot-starter-camunda</artifactId>
            <version>8.4.2</version>
        </dependency>
        
        <dependency>
            <groupId>io.camunda</groupId>
            <artifactId>zeebe-client-java</artifactId>
            <version>8.4.5</version>
        </dependency>

Create the zeebe-client with some basic grpc calls and start the application, you can see the error at the application start up. 

application.yml

zeebe:
  client:
    broker:
      gateway-address: "127.0.0.1:26500"
    security:
      plaintext: true

**Expected behavior**

There should not be any error message at application start up. 

**Log/Stacktrace**

<img width="1766" alt="Screenshot 2024-04-05 at 1 39 33 PM" src="https://github.com/camunda-community-hub/spring-zeebe/assets/61071346/b70901de-7bc9-4371-bf37-a6a93d9dfb93">

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Deployment: Self-managed zeebe 8.4.5
- Spring-Zeebe Version:8.2.4
- SpringBoot Version: 3.2.4
- Configuration:

**Comment by jonathanlukas** [comment]
The used configuration is deprecated. Please review the configuration on how to configure the zeebe client

**Comment by dgilsonAfelio** [comment]
Hello, I got same issue but can't use new config in **zeebe-simple-monitor** because it doesn't take into acount `camunda.client.zeebe.gateway-url` but only `zeebe.client.broker.gateway-address`

**Comment by jonathanlukas** [comment]
@dgilsonAfelio did you open an issue in zeebe-simple-monitor?

**Comment by jonathanlukas** [comment]
@srinath-seralathan this issue is resolved in the official sdk.

**Comment by jonathanlukas** [comment]
@srinath-seralathan the official sdk docs can be found here: https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/

**Comment by srinath-seralathan** [comment]
@jonathanlukas  Thank You let me refer it. Once resolved let me share my comments

**Comment by srinath-seralathan** [comment]
> [@srinath-seralathan](https://github.com/srinath-seralathan) the official sdk docs can be found here: https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/

@jonathanlukas Thank You Very much. the above docs helped to resolve this issue. But Users make sure to provide Complete Properties Variable without any mistake.
