### ISSUE TITLE
Camunda private dependencies

### ISSUE THREAD

**Issue by stephanpelikan** [camunda-community-hub/spring-zeebe#783]
**Describe the bug**

As a community user I want to use Zeebe without having access to Camunda's artifactory. There are dependencies to private artifacts (e.g. https://github.com/camunda-community-hub/spring-zeebe/blob/main/pom.xml#L108).

**Expected behavior**

1. The dependency is either marked as optional or in the README.md is mentioned how to run it without those dependencies (e.g. by using Maven-excludes).
2. The Spring Zeebe integration works even if all Camunda clients are disabled (e.g. `camunda.client.operate.enabled: false`).
 
**Environment:**
- OS: Linux/Windows
- Deployment: SM 8.5.0 
- Spring-Zeebe Version: 8.5.2
- SpringBoot Version: 3.2.3 
- Configuration: only `camunda.client.zeebe.enabled: false` all other clients are disabled

**Comment by jonathanlukas** [comment]
The identity sdk has been published: https://central.sonatype.com/artifact/io.camunda/identity-sdk/8.5.3
