### ISSUE TITLE
`fetchVariables` should support patterns

### ISSUE THREAD

**Issue by namero999** [camunda-community-hub/spring-zeebe#894]
`@JobWorker` annotation parameter `fetchVariables` should support patterns to allow for more flexibility while still limiting the amount of variables transmitted.

Imagine a scenario where you have multiple tasks and each of them emits an "outcome" variable of sort, but you can't resolve each variable name as maybe such name is a function of the task id or something...

It would be ideal if we could say for instance

```
@JobWorker(type = "finalProcessor", fetchVariables = {"*_status"})
```

and find all variables that match into `job.getVariablesAsMap()`

**Comment by jonathanlukas** [comment]
@namero999 the fetchVariables parameter in the @JobWorker annotation represents the fetchVariables parameter from the activateJobs grpc command where a pattern is also not supported. 
Please request this feature from camunda/camunda
