### ISSUE TITLE
Can a Spring Zeebe client with version 8.5 connect to zeebe version 8.1?

### ISSUE THREAD

**Issue by mashimaro7646** [camunda-community-hub/spring-zeebe#914]
Can a Spring Zeebe client with version 8.5 connect to zeebe version 8.1? The server previously installed zeebe version 8.1 and is currently using it in production. Now due to security issues, the client needs to upgrade spring to version 3.3, so spring zeebe also needs to be upgraded to 8.5. However, it is difficult to upgrade the production zeebe to 8.5, so I want to try to use the 8.5 client to connect to zeebe.

**Comment by sephiroth-j** [comment]
No, the Zeebe client 8.5 can only communicate with Zeebe that have the same or a newer version.

see also [Version compatibility of 8.5](https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/#version-compatibility)

**Comment by mashimaro7646** [comment]
Thank you so much
