### ISSUE TITLE
Turn Health Zeebe indicator off by default

### ISSUE THREAD

**Issue by salaboy** [camunda-community-hub/spring-zeebe#94]
This PR added the Zeebe Health indicator: 
https://github.com/zeebe-io/spring-zeebe/pull/87

But it is enabled by default, causing the entire Spring Boot application to be marked as DOWN if the Zeebe Cluster configured cannot be reached. 

The PR introduced a flag to turn it off.. so I propose to set the default to false and ask users to turn it on, if they have that required behaviour.

**Comment by berndruecker** [comment]
+1 if we add documentation on how to turn it on in the readme (as all "pure" workers will probably use that)

**Comment by berndruecker** [comment]
I close this for now as it did not come up in any real-life context yet
