### ISSUE TITLE
Clarify the relation of this project and https://github.com/camunda/camunda/tree/main/clients/spring-boot-starter-camunda-sdk/src/main/java/io/camunda/zeebe/spring

### ISSUE THREAD

**Issue by fml2** [camunda-community-hub/spring-zeebe#978]
**Description**

The two projects are very similar. Does one of them supecede the other?

**Comment by jonathanlukas** [comment]
See docs: https://github.com/camunda-community-hub/spring-zeebe?tab=readme-ov-file#spring-zeebe

**Comment by jonathanlukas** [comment]
TL;DR: This project will be discontinued shortly

**Comment by fml2** [comment]
Could you please write it as the first line in README?
